### ISSUE TITLE
Inclusion/Exclusion Criteria

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#100]
[JIRA DDF-455](https://jira.cdisc.org/browse/DDF-455)

I was not able to find Inclusion/Exclusion criterial in the USDM UML diagram, but I believe they are important study design information that appears repeatedly in the study protocol document, on an EDC form, and in the SDTM TI dataset.

I would suggest adding Inclusion/Exclusion Criterion class to the UML and an attribute for I/E criteria to the StudyDesignPopulation class (as indicated in the ICH M11 CeSHarP).

Child tickets:

| Item  | Ticket |
| ------------- | ------------- |
| Model | #129 |
| CT | #130 |
| API | #130 |
| IG |  # |
| Examples |  # |

**Comment by BSnoeijerCD** [comment]
Note: The direct link to inclusion/exclusion criteria should be from studyDesign. There might be a crosslink to studyPopulation but that is depending on our cohort discussion which will take place at coming SME meeting next Tuesday at 10 AM EST. Please attend that one to understand the difficulties.
For this sprint we can align with M11 and TI trial design domain. 
For CT team: Add text attributes that align with both. For Dev team to add the new class and attributes to the model.

**Comment by BSnoeijerCD** [comment]
Additional note: This also relates to text templates. Once they are fully developed and in place, we can link the full text versions of the eligibility criteria to the text template facility of the data model.

**Comment by BSnoeijerCD** [comment]
For planning meeting: 
Requirements:
- include Structured content for each criterium separately so that it easily maps to SDTM TI domain and can be exported to CT.gov. The content class can be used for that.
- add attribute to indicate what kind of criterium: IN- or EXclusion
- Add attribute to indicate number of criterium (order of presentation)  
This means that we need a new class that refers to the content class for the structured text.
Inclusion and Exclusion criteria are combined as Eligibility criteria. Therefore, a new class named eligibility makes most sense. 
Dave presented both the whole eligibility text parts and the individual criteria items as class in his diagram but probably the lower level per criterium is enough.
My proposal for this sprint would be like this:
![image.png](https://images.zenhubusercontent.com/64a55ab2667288627de4e279/1f35cb24-a2e4-48fe-854c-0141af172c44)

**Comment by BSnoeijerCD** [comment]
@czwickl @EMuhlbradt @daveih 
See this example of how the eligibility content can be stored in the content class (First tab):
[EligibilityCriteria Content Example.xlsx](https://github.com/cdisc-org/DDF-RA/files/12336594/EligibilityCriteria.Content.Example.xlsx)
The second tab shows how the additional information linking to M11 tech specs (item numbering) , SDTM (type and numbering) and CTIS (type) can be stored with the direct link to the corresponding content.

Looking forward to your comments and questions.

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @czwickl @daveih @jared-schreibman-cdisc : 
For this design we need a new class eligibility: with attributes id, name, type, number and reference to syntax text template class.
The eligibility text in the content class will then have a link to the eligibility class.

See updated Excel with example of the new class Eligibility (containing inclusion and exclusion criteria) and how the text in the content class will refer to that. 
Question for @dih-cdisc: Should we not also include the attribute in this reference? 

[EligibilityCriteria Content Example.xlsx](https://github.com/cdisc-org/DDF-RA/files/12417767/EligibilityCriteria.Content.Example.xlsx)

**Comment by dih-cdisc** [comment]
Note discussion from Scrum of 23 Aug 23. The Eligibility class should be derived from SyntaxTemplate

Also adding the diagram used at SME meeting of the 22 Aug 23 which shows the context of this

![2023 08 22 InclusionExclusion](https://github.com/cdisc-org/DDF-RA/assets/115090009/86cc7385-18a0-4ba0-b33d-ea266adcae32)

**Comment by dih-cdisc** [comment]
Design Sketch

![DDF USDM Model Informative](https://github.com/cdisc-org/DDF-RA/assets/115090009/822f08cc-6179-4d61-b2f7-cc57e5267933)

**Comment by drewcdisc** [comment]
SyntaxTemplate needs InstanceType attribute
