### ISSUE TITLE
Cohorts

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#109]
Several informal comments received regarding Cohorts along with one public review comment:

[JIRA DDF-454](https://jira.cdisc.org/browse/DDF-454)

How to represent data for studies with multiple Arms/Groups/Cohorts having general and specific Objectives, Endpoints, and Inclusion-Exclusion criterias?

This needs to be looked at as part of Phase 3

Child tickets:

| Item  | Ticket |
| ------------- | ------------- |
| Model |  #186 |
| CT |  #187 |
| API | #185 |
| IG | #188 |
| Examples | #189  |

**Comment by dih-cdisc** [comment]
It would be useful to have an example protocol that exhibits these features so we can clearly see the issues

**Comment by dih-cdisc** [comment]
Also see [DDF-RA 445](https://jira.cdisc.org/browse/DDF-445)

**Comment by dih-cdisc** [comment]
First sketch design as discussed within Cohorts working group and SME meeting

![2023 10 23 Cohorts](https://github.com/cdisc-org/DDF-RA/assets/115090009/60661ade-bc35-40a8-9c5c-e1304460a0a9)

**Comment by dih-cdisc** [comment]
Updated design sketch

![2023 10 31 Cohorts](https://github.com/cdisc-org/DDF-RA/assets/115090009/27591275-1a03-4fa9-8f66-6ee11baec24b)

**Comment by BSnoeijerCD** [comment]
Thank you. 

 @dih-cdisc: Based on this I have the following questions:
-  I was wondering what the Range attribute would be. Do you want to add min/max attributes or a new range class (which will become a datatype later). Should the min and max refer to the quantity class?
- I think we presented the quantities as relationships in 2.6. But as it is more like a data type, should it not be presented in CT in as attributes as we do for code? If we don't do that, we might loose the semantics if we only express it as a relationship.

- The name characteristic for the new class seems very general. Unless you want to reuse it for other parts of the model as well, I suggest to call it CohortCharacteristic 
- CompletionNumberOfParticipants might be confusing as we are not collecting the information on how many subjects have completed the study at the end, but what is planned to be completed. Would something like the following be better?
     - plannedNumberEnrolled
     - plannedNumberCompleted
@EMuhlbradt, @czwickl : Any thoughts? We include "OfParticipants" now in all attribute naming but they become very long like this.

**For the CT the above model would implicate the following changes:**
- Move all attributes from StudyDesignPopulation to new class population. 
- Change plannedNumberOfParticipants according to answer on first question above
- Add new attribute completionNumberOfParticipants according to answer on first question above
- Change plannedMinimumAgeofParticipants and plannedMaximumAgeofParticipants to relationships to the quantity class. See also my question above.
 - StudyDesignPopulation does have 1 additional relationship: cohorts pointing to the new cohort class.
- Cohort will also inherit everything from Population and has 1 additional relationship to characteristic.
- The new class characteristic needs to be created and inherits all attributes of syntaxTemplate

**Note:** since for the CT we have now decided to represent all attributes both for the main class and the classes that inherit them, this will mean that the (changed) attributes of population will also be added to studyDesignPopulation (as before) and Cohort classes. And that the attributes of SyntaxTemplate will be copied to the new class Characteristic

**Comment by dih-cdisc** [comment]
Responses

1. Range should be a class like Quantity (2 attributes, min and max)
2. Quantity is another simple class but is really a datatype longer term (FHIR preferably)
3. Yes, characteristic is general, but then it is a general idea. It is scoped by Cohort but it may get used elsewhere
4. Names here do need some work by @EMuhlbradt and @czwickl ... I did not want to change the name of the existing attribute but was thinking it could be better named given the new one.  We need our target recruitment and the overall number we need to recruit to get that target given dropouts

**Comment by BSnoeijerCD** [comment]
@dih-cdisc @EMuhlbradt @czwickl:  See UML proposal for based on the above diagram. I only showed the relevant classes and added questions regarding relationships and naming. 
![Population_cohort](https://github.com/cdisc-org/DDF-RA/assets/138679324/ac1c951a-d6b6-4d30-a413-da0ac9772d1e)

Note that in the final UML you will see the inherited attributes as well. It did not show in this subversion.

**Comment by BSnoeijerCD** [comment]
Just for your info. Here is the total picture.
![USDM_UML_2 7](https://github.com/cdisc-org/DDF-RA/assets/138679324/c4709b58-c762-433d-be8c-36a6e093d3fe)

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @czwickl @dih-cdisc: Updated UML as per our discussion.
![Population_cohort_2](https://github.com/cdisc-org/DDF-RA/assets/138679324/1ca21f7e-a034-4606-9740-42fdae22bc8a)

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @czwickl @dih-cdisc  Updated with new questions as discussed during scrum today
![Population_cohort_3](https://github.com/cdisc-org/DDF-RA/assets/138679324/86996c7b-7b74-4750-8238-44c6f855d5ed)

**Comment by dih-cdisc** [comment]
Re anticipatedValue, see comment [here](https://github.com/cdisc-org/DDF-RA/issues/187#issuecomment-1813834068)

I think it should be a boolean value, "this range is approximate". 

Also, as an aside, we need the rule for a single value (just set min or set min and max to same value) for the IG
