### ISSUE TITLE
Blinding/Unblinding [CT/Model]

### ISSUE THREAD

**Issue by drewcdisc** [cdisc-org/DDF-RA#122]
Part of #119.

This will require the creation of our first implementation of Text Blobs on order to deliver this.

**Comment by EMuhlbradt** [comment]
[M11 Brainstorm for DDF_Blinding and Unblinding.xlsx](https://github.com/cdisc-org/DDF-RA/files/12126602/M11.Brainstorm.for.DDF_Blinding.and.Unblinding.xlsx)

**Comment by dih-cdisc** [comment]
@EMuhlbradt Image I used on scrum call 25th July

![2023 07 25 Sections](https://github.com/cdisc-org/DDF-RA/assets/115090009/dca9b877-f71d-406a-ab75-94ade3ba431d)

**Comment by MarkPAndrews** [comment]
@EMuhlbradt @czwickl 
Per our discussion this morning I've attached 2 options for modeling these elements.
Option 1 uses the "Section" approach in @dih-cdisc diagram.
![image](https://github.com/cdisc-org/DDF-RA/assets/8182469/87057fe9-177d-4d59-b047-f300b47f1fb6)
Option 2 uses the approach mentioned in the note under "blinding" where it is just a text blob.
![image](https://github.com/cdisc-org/DDF-RA/assets/8182469/c19416b4-78db-4aef-adc2-0a6eea18091e)
Let me know if I have missed anything.  We should discuss if in Option 2, `text` should be a list of strings.
CC @BSnoeijerCD

**Comment by BSnoeijerCD** [comment]
Hi all,

We need certainly the content class as indicated above.  Because we need to reuse that for other parts of the model.

What would be stored in the new blinding / unblinding classes? If it is only 1 row per content item then it seems superfluous to create separate classes for it. Then the content class alone is enough for now (like the TS domain of SDTM).

In the content class, we can indicate the contentType and in such way divide the different content areas to the specific domains. Like you did with  scheduledInstance and scheduledInstanceType (activity or decision). 
ContentType could then be (unblinding / blinding / etc) .  
If we have other more structured information that we want to model then we can link the corresponding content parts to that but for now I think it is not necessary to create a number of almost identical classes.

**Comment by EMuhlbradt** [comment]
@BSnoeijerCD, Here is the verbatim text from the M11 template regarding the Emergency Unblinding data element:

"Describe the criteria for breaking the trial blind or participant code. Discuss the circumstances in which the blinding would be broken for an individual or for all participants (for example, for SAEs) and who has responsibility. Include the procedure for emergency unblinding such as via IVRS/IWRS or code envelopes as well as documentation of unblinding. Indicate to whom the intentional and unintentional unblinding should be reported."

**Comment by EMuhlbradt** [comment]
@czwickl, I think 'Type' isn't the correct word to use here given our very specific usage of that word 'type' in Phases 1 and 2 of project development. Can we consider a different name to share with the dev team?
'contentParameter'
'parameterName'
'parameterTitle'

Thoughts?

Also, question for the whole group...what is meant to be the value for the 'name' attribute of the Content entity? I'm struggling to define it so that it is distinct from the expected list of value 'names' for the contentType attribute (or whatever we end up calling it) above.

**Comment by czwickl** [comment]
Based on our team discussion yesterday and Mark's updated figure, I think we could call these things either "ContentSubsection" or "ContentSubtopic" instead of "ContentType". I lean more toward the first, as it is more aligned with the idea of the content being associated with particular subsections of a protocol. All major sections could be part of the "subsections" class since they are single pieces of a complete protocol, so the word "subsection" is safe for everything.

**Comment by MarkPAndrews** [comment]
@BSnoeijerCD Should ContentParameter be another enumeration like ContentTopic or is a String good enough?

**Comment by BSnoeijerCD** [comment]
@MarkPAndrews String is good enough for content topic. ContectText should have richText formatting included.

**Comment by MarkPAndrews** [comment]
Here is the new partial UML.
![image](https://github.com/cdisc-org/DDF-RA/assets/8182469/158d199f-3989-4f0f-b641-afdc41c0582c)

**Comment by MarkPAndrews** [comment]
Per our conversation in the stand up:  Here is the new model.
![image](https://github.com/cdisc-org/DDF-RA/assets/8182469/935fda3e-93c0-4232-be98-68ff7e1d5ff4)

**Comment by MarkPAndrews** [comment]
Per our conversation in the stand up: Here is the new model.
![image](https://github.com/cdisc-org/DDF-RA/assets/8182469/2a7108af-446b-438e-b898-534c6d223a6b)

**Comment by dih-cdisc** [comment]
@BSnoeijerCD @MarkPAndrews Some observations

1. sectionName -> sectionTitle, I think title is the more obvious label for this, e.g. "1.1.2 Section On Boring Stuff" -> Number = "1.1.2" and Title = "Section On Boring Stuff"
2. Content should be able to recurse so that subsections can be held
3. text and the RichText datatype. I think we should not use RichText, not a great standard. [x]html would be better, given it is W3C

Worth looking at 

[HL7 FHIR compositon resource](https://build.fhir.org/composition.html) and the section class. Note they have [Narrative](https://build.fhir.org/narrative.html#Narrative) type for the text. Slightly more elaborate than we might need but xhtml based.

**Comment by BSnoeijerCD** [comment]
@dih-cdisc Good points.

1. Changing sectionName to sectionTitle makes it even more clear. In addition to the above, we also decided to add Name to address the M11 name of the content.
2. We decided to leave the recurse part for a next iteration when needed. So we can add that later and discuss the implications. 
3. @MarkPAndrews : Can you change this the type for Text as indicated by Dave? And also the SectionName to sectionTitle?

We discussed the contentTypes. We started with that to begin with but we had the issue that this is in a number of cases can overlap and seemed superfluous to the sectionTitles and numbers. So we decided to leave it out for now and see whether it is necessary in the future. 

@jared-schreibman-cdisc , @EMuhlbradt @czwickl -> see comment of Dave on SectionTitle

**Comment by MarkPAndrews** [comment]
@dih-cdisc @BSnoeijerCD Here is the updated model.  I changed `text` to a `String` which should be fine to hold the (X)HTML.  We can note in the CT the intent to have the contents of `text` be HTML.
![image](https://github.com/cdisc-org/DDF-RA/assets/8182469/27a742c7-4e2f-4a5e-b842-77e60dbc422d)

CC @EMuhlbradt

**Comment by BSnoeijerCD** [comment]
As just discussed: Add contentParent in the content class as a self-reference to the content class.
Note: for the API it should be contentParentId !

**Comment by MarkPAndrews** [comment]
![image](https://github.com/cdisc-org/DDF-RA/assets/8182469/70ba2dd4-b2a1-4921-9327-4720b0b4210b)

**Comment by BSnoeijerCD** [comment]
@jared-schreibman-cdisc : The final following attributes are added for the new content class/entity (as you can see in the scheme above):
id
SectionNumber
SectionTitle
Name
Text 
contentChildren 

content class needs to be nested in the StudyDesign class.
contentChildren is a reference to itself: so it should be have format text in the API with the addition of "Ids" to the attribute name => contentChildrenIds (as per rules that we defined in the previous sprint).
