### ISSUE TITLE
Required attributes

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#127]

**Comment by BSnoeijerCD** [comment]
There are a number of items in the API required that can cause problems in using the API. While on the other side the ID values do not seem to be required.
I would propose to add the required information to the CT spreadsheet so that Erin and Craig can be included in the evaluation and we have this information in a readable form. 

For example standardCode in class AliasCode is required? In some cases there is not (yet) a standard CDISC code known or available and this prevents users to add other alias codes as well. Also for example: bcReference and bcConceptCode. Especially bcReference is not correct in my opinion.

**Comment by drewcdisc** [comment]
Jared will remove all the 'required' meta-properties for attributes for now.

**Comment by dih-cdisc** [comment]
Several observations on this ticket @BSnoeijerCD @jared-schreibman-cdisc @drewcdisc.

The statement "There are a number of items in the API required that can cause problems in using the API" needs some justification / evidence. Also, "While on the other side the ID values do not seem to be required." seems odd given that none of the cross references would work without them.

Note sure what is meant by "I would propose to add the required information to the CT spreadsheet so that Erin and Craig can be included in the evaluation and we have this information in a readable form." what "required information"?

As for "For example standardCode in class AliasCode is required? In some cases there is not (yet) a standard CDISC code known or available and this prevents users to add other alias codes as well.". AliasCode is used in the following attributes:

- Study - studyPhase
- StudyDesign - studyDesignBlindingScheme
- BiomedicalConcept - bcConceptCode
- BiomedicalConceptProperty - bcPropertyConceptCode
- BiomedicalConceptCategory - bcCategoryCode

The first two have CDISC CT defined. The other three cannot have a single code list specified but will have NCI codes from the definition of the BC held within the CDISC library.

"Also for example: bcReference and bcConceptCode. Especially bcReference is not correct in my opinion."

For bcReference, this attribute is defined as a string. A string can be empty. The definition in the API python might be updated to `Union[str, None] = None` to make it more explicit but, technically, it is correct.

So I suggest holding back on changing anything for this one.

**Comment by BSnoeijerCD** [comment]
@daveih 
- If you look at the API you can see that whether an attribute is required is very random. Id values are not required anywhere while for example the address related to an institution is and the only required field in endpoint is endpointpurposedescription while it is even not clear to most users what should be in there. 
- We discussed with the team that whether fields were required is now just randomly added in the API without clear substantiation and documentation. 
- We also discussed that the CORE rules will take over the requirements as a validation of the complete data. While the API should be able to also exchange partial study information.
- We wanted to discuss with you more on what would be the standard required variables and why. Therefore we decided to remove the requirements for now so that they can be added based on proper substantiation and documentation.
- I believe this will help the implementations as I also experienced that the Accenture team had to add manual text to the API input to be able to parse the required fields. Although our team believes they can be empty although required: not all implementations teams apparently evaluate that in the same way as you intended. And then again why not require id values to be available. 

See example required endpoint fields in the API:
        "type": "object",
        "required": [
          "endpointPurposeDescription"
        ],

**Comment by BSnoeijerCD** [comment]
As discussed with Dave: don't remove requirements. See release 2.0. The requirements/mandatory fields that are specified should be maintained. Id an name should be mandatory and description should be optional.

**Comment by dih-cdisc** [comment]
@BSnoeijerCD 

This looks like we have a bug introduced in Phase 3, sprint 1. Have a look at the initial ticket where we did the work, there is some code where I did some playing on getting FastAPI to generate the correct id, name, description mandatory/optional [see here](https://github.com/cdisc-org/DDF-RA/issues/35#issuecomment-1623375238)

**Comment by jowencdisc** [comment]
Related to JIRA https://jira.cdisc.org/browse/DDF-473 internal review comment
