### ISSUE TITLE
Syntax Templates [CT/Model]

### ISSUE THREAD

**Issue by drewcdisc** [cdisc-org/DDF-RA#135]
Implement design in #120

**Comment by EMuhlbradt** [comment]
[DDF Sprint 4_backlog item 135 - Syntax Template terms.xlsx](https://github.com/cdisc-org/DDF-RA/files/12429037/DDF.Sprint.4_backlog.item.135.-.Syntax.Template.terms.xlsx)

Attached are the semantics concerning the two syntax template entities and attributes

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @czwickl : I think I miss the reference from syntaxTemplate to syntaxTemplateDictionary.
Should be something like: The dictionary used to complete the referenced fields in the templateText 
(But then in better wording of course ;) )
@daveih you also might want to review.

**Comment by EMuhlbradt** [comment]
@BSnoeijerCD , @czwickl ; We didn't want to use the word 'dictionary' in the definition so instead described that part as 'A reference source that provides a listing of...'. That being said, we could consider being more descriptive instead of saying 'used in'.

Original Def: A reference source that provides a listing of valid parameter names and values used in syntax template text strings.

Options to consider:
1. A reference source that provides a listing of valid parameter names and values used to populate syntax template text strings.
or
2. A reference source that provides a listing of valid parameter names and values used to populate syntax template text strings.

@BSnoeijerCD I think the inclusion of the phrase 'syntax template text strings' at the end covers the link back to the SyntaxTemplate class.

@czwickl , thoughts?

**Comment by BSnoeijerCD** [comment]
Hi @EMuhlbradt and @czwickl : 
Sorry, I should be more clear: We need the relationship from syntaxTemplate to syntaxTemplateDictionary. I missed that in the excel you send. 
I think both options above are identical. Did you have another options as well? 
It provides a listing of used parameters and corresponding pointers or values.

**Comment by dih-cdisc** [comment]
> [DDF Sprint 4_backlog item 135 - Syntax Template terms.xlsx](https://github.com/cdisc-org/DDF-RA/files/12429037/DDF.Sprint.4_backlog.item.135.-.Syntax.Template.terms.xlsx)
> 
> Attached are the semantics concerning the two syntax template entities and attributes

@EMuhlbradt Couple of comments:

1. would suggest an attribute name change from templateText -> text (same as in Content class)
2. The attribute of type relationship from SyntaxTemplate to SyntaxTemplateDictionary which I would name "parameters"
