### ISSUE TITLE
Check Cardinality [API]

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#145]
Set of model cardinality settings that need checking and changes made if found to be wrong. Item numbers refer to the row numbers in column A of the attached spreadsheet.

See rows 74, 101, 106, 107,  129, 200
Final decisions: 
74: endpoint.endpointlevel: change cardinality to 1
101: encounter.encounterScheduledAtTiming: keep cardinality at 0..1 => No change
106: encounter.encounterType: change cardinality to 1
107: encounter.encounterEnvironmentalSetting: keep cardinality at 0..1 => No change
129: 
estimand.treatment: change cardinality to 1
estimand.variableofinterest: change cardinality to 1
200: scheduleTimeline.scheduleTimelineEntry: change cardinality to 1

[USDM_CT_Required.xlsx](https://github.com/cdisc-org/DDF-RA/files/12415471/USDM_CT_Required.xlsx)

**Comment by dih-cdisc** [comment]
@BSnoeijerCD  @jared-schreibman-cdisc Just an image from the spreadsheet of all the rows mentioned above, make it easier to see them. These are tidy-up changes, just review them and see if a change is necessary (might not be).

Note: At some point in time we want to get these cardinalities into the UML inside of EA, don't forget that.

![Screenshot 2023-09-12 at 13 09 04](https://github.com/cdisc-org/DDF-RA/assets/115090009/a85930c3-ce2d-46c1-95ca-1e7f2f6b31f0)

**Comment by BSnoeijerCD** [comment]
@daveih @jared-schreibman-cdisc 
Notes:
Row 74: endpointLevel will be changed to Level (See ticket #98). Discuss with team whether endpoint always needs a level. As objectives already have a level and are linked to endpoints. The endpoint level might be superfluous. However, as discussed in phase 1 with the SMEs, some companies might have a secondary endpoint linked to a primary objective. 
Row 101: According to my opinion an encounter should have a timing. That is the basic principle of an encounter. Could be the same as the timing of scheduledinstance. 
Row 106/107: encountertype and encounterenvironmental setting might also have been changed to Type and EnvironmentalSetting already (to be checked). To discuss whether we this must be completed. I tend to have the first one 1 and keep the environmentalsetting at 0..1
Row 129: An estimand combines 1 analysispopulation with 1 endpoint (variableOfInterest) and 1 or more intercurrent events. So, given that: 1 is ok for this one.
Row 200: To discuss. I tend to say 1. What happens if it is 0?

**Comment by dih-cdisc** [comment]
@BSnoeijerCD @jared-schreibman-cdisc 

Row 74: Endpoint has a level, we have had this discussion previously as part of the public review, see https://jira.cdisc.org/browse/DDF-438 
Row 101: It is whether we constrain the model at the current time?
Row 129: Need to look at the entire set, the set is inconsistent, see image below
Row 200: Implication is you have a timeline with no start point, would be a little odd

![Screenshot 2023-09-13 at 07 14 07](https://github.com/cdisc-org/DDF-RA/assets/115090009/2c17a375-7f08-4df4-87c1-308da3903171)

**Comment by BSnoeijerCD** [comment]
@dih-cdisc based on the points above I would then suggest the following:
74: endpoint.endpointlevel - Set to 1 instead of 0..1
101: encounter.encounterScheduledAtTiming: Set to 1 instead of 0..1 
(I believe it should be constrained and is save to do so. But if you want to leave it for now that is ok with me). 
106: encounter.encounterType: change cardinality to 1 (already decided above)
107: encounter.encounterEnvironmentalSetting: keep cardinality at 0..1 => No change (already decided above)
129:
estimand.analysispopulation Keep at 1
estimand.treatment ?  Set to 1 instead of 0..1
estimand.variableofinterest ? set to 1 instead of 0..1
200: scheduleTimeline.scheduleTimelineEntry ? set to 1 instead of 0..1

Can you agree on that? Then I will update it above to make it clear to the team.

**Comment by dih-cdisc** [comment]
All good except for "101: encounter.encounterScheduledAtTiming: Set to 1 instead of 0..1" Just being cautious on this one, leave it as is. We can always make a separate ticket just for it and place in backlog so we recheck it.

**Comment by BSnoeijerCD** [comment]
@jared-schreibman-cdisc : documented final decisions in description of ticket above. So you have 1 overview. 
You are good to go to make the changes
FYI: @dih-cdisc @drewcdisc

**Comment by BSnoeijerCD** [comment]
Reviewed: Except for the first change indicated in the descriptions above - other changes did not yet land in final API.
