### ISSUE TITLE
Generalization/Specialization class definitions

### ISSUE THREAD

**Issue by ASL-rmarshall** [cdisc-org/DDF-RA#196]
There appear to be three general classes defined in the model:
- `GeographicScope`, with specialization:
    - `SubjectEnrollment`
- `ScheduledInstance`, with specializations:
    - `ScheduledActivityInstance`
    - `ScheduledDecisionInstance`
 - `SyntaxTemplate`, with specializations:
     - `EligibilityCriteria`
     - `Endpoint`
     - `Objective`

Are there expected to be instances of the general classes? For `ScheduledInstance` and `SyntaxTemplate`, only the specializations are referenced in the API specification, which seems to indicate that instances of these general classes are not expected/allowed. Both `GeographicScope` and `SubjectEnrollment` are referenced in the API spec, which implies that instances of both are expected/allowed.

If instances of `ScheduledInstance` and `SyntaxTemplate` will never be expected/allowed, it would be helpful to flag these as abstract classes in the UML model.

There doesn't seem to be anything in the Data Dictionary to indicate generalization/specialization. It might be helpful to:
- Exclude abstract classes from the Data Dictionary listing (because there'll never be "data" for them)
- Represent the attributes and relationships of the general class in each of their specializations so that there's a full listing of the attributes/relationships expected for each of the specializations. (This piece looks to be the similar to #191)

**Comment by dih-cdisc** [comment]
Generally the specialisations are the ones used in the API. The exception is GeographicScope which will be seen along with SubjectEnrollment.

**Comment by ASL-rmarshall** [comment]
@dih-cdisc Yes. When you included `ScheduledInstance` and `SyntaxTemplate` in the model, I think you included them as a modelling convenience - they're in the model so you don't have to have multiple copies of the same thing - but you're never expecting there to be instances of them.  If this is correct, this is a modelling decision (not a serialization choice), so it would be helpful to mark them as abstract classes in the model:
![image](https://github.com/cdisc-org/DDF-RA/assets/113628824/7823d889-96b3-4a6b-ad7a-4c204d0c9e67)
This will save people wondering why they're not included in the API spec.  Thanks

**Comment by BSnoeijerCD** [comment]
@ASL-rmarshall : Thank you. I can change that in 2.7 version of UML. Then we have time to check the effects.
@dih-cdisc: As we do now show/repeat all attributes in CT for the specialization classes, do you think we should remove the generalized classes. At least, I think it is helpful to indicate that they will not be used on it's own.

**Comment by ASL-rmarshall** [comment]
@BSnoeijerCD Only the *abstract* generalized classes should be removed, I think. You can get instances of `GeographicScope`, so it makes sense to keep it in the data dictionary.

**Comment by dih-cdisc** [comment]
We will not remove the abstract classes from the Data Dictionary or CT because of the variety and varied consumers of the USDM, e.g. vendors, because if they wish to extend the model they may wish to build on the abstract classes.

We can mark the abstract classes in the UML which will, hopefully, propagate to the XMI, In the DD we can add a flag to indicate the abstract classes and also flag inherited attributes and relationships in classes inheriting from the abstract classes. 

I have already asked @gerrycampion to look into this at a sensible time. It is better to provide the full information and let model consumers decide what they wish to do for their use case; use cases which we may not be able to predict.

Please remember that CORE is but one user of USDM, there are many others.
