### ISSUE TITLE
Why isn't plannedSexOfParticipants listed as an attribute in the UML class of StudyDesignPopulation?

### ISSUE THREAD

**Issue by rbakercdisc1** [cdisc-org/DDF-RA#198]
Why isn't plannedSexOfParticipants listed as an attribute in the UML class of StudyDesignPopulation? I see it noted in one of the lines but not listed as an attribute.

**Comment by dih-cdisc** [comment]
@BSnoeijerCD We will check this, there are some other checks we need to look at to ensure perfect alignment between the UML, CT and API

**Comment by BSnoeijerCD** [comment]
@rbakercdisc1 @dih-cdisc :  All attributes with standard CT or relate to other coding systems are represented by lines in the UML because they are actually relationships to the code or aliascode class. It would be double if we added it both as an attribute and as a relationship. 
<img width="131" alt="StudyPopulationv2 6" src="https://github.com/cdisc-org/DDF-RA/assets/138679324/4bdc1812-bd70-49e6-9d16-633f1dd47fc1">
