### ISSUE TITLE
Organization.type CT values [CT]

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#258]
Organization.type with CT code C188724 now includes Clinical Study Sponsor, Clinical Study Registry, Regulatory Agency. This is not applicable for the ResearchOrganization class which is inheriting the organization attributes.
Type is required. 
Can we add types to CT to cover research organization?

See child tickets:

| Item  | Ticket |
| ------------- | ------------- |
| Model |  #287 |
| CT | this ticket |
| API |  #286 |
| IG |  #288 |
| Examples |  #289 |

**Comment by EMuhlbradt** [comment]
@BSnoeijerCD @dih-cdisc We think that this comment is asking us to extend the Organization type codelist (C188742) with additional values that are types of Research Organizations. However there is no indication from the values what additional terms are needed? Research Organization Types: CRO, Academic Institute, Biopharmaceutical Company, Government Institute, Non-Profit Society/Foundation, etc.

An additional FYI is that a Research Organization is in itself a type of Organization (parent/child relationship). Because we are re-using the codelist for both classes, this means that some items in the codelist 'Organization Type' are not going to be relevant values for ResearchOrganization.type. Is this okay or do we need two separate codelists? However, any of the organizations/research organizations could be considered a sponsor as well. Is there a distinction to be made between 'type' and 'role'?

**Comment by BSnoeijerCD** [comment]
As discussed during the scrum today: 
While adding values to Organization.type we realized that when inherited the attribute 'type' gets another semantic meaning (researchOrganzation.type). Therefore, we decided for now to rename the attribute to organizationType for this release. Corresponding child tickets for model, API, IG and test data are created as referenced above.
