### ISSUE TITLE
Condition Class Relationships

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#265]
These comments received from Accenture

- DDF-483
  - ScheduledInstance --> InstanceType attribute is marked as non-mandatory in V2.8 and API will not be able to parse the Activity/Decision instance data if the InstanceType is not specified. Please confirm if this attribute will be marked as mandatory in future releases.
  - Also, the Enum/constant values ACTIVITY/DECISION for this attribute mentioned in previous releases will no longer be valid and corresponding class names must be used for this attribute to identify the instance type. Please confirm.
- DDF-484
  - InstanceType non-mandatory attribute added to all classes in API specification. Please let us the objective/business use case behind this change.
  - Are there any additional requirements to be considered from an API implementation perspective for the upcoming SDR release V3.0?
- DDF-485
  - As per our understanding, basic validation to be added in API Implementation for appliesToIds and contextIds attributes under condition class as mentioned below. Please confirm.
    - contextIds : a valid element Id from one of the classes (Activity and ScheduledActivityInstance)
    - appliesToIds : a valid element Id from one of the classes (Activity, ScheduledActivityInstance, Procedure, 
  -BiomedicalConceptSurrogate, BiomedicalConceptCategory and BiomedicalConcept)
  - It is mentioned during one of the SME meetings that overlapping of element Ids from different classes should be avoided for these attributes. Please confirm if this validation to be done at Study Builder end (or) additional validation rules to be added in the API Implementation."

**Comment by dih-cdisc** [comment]
Couple of actions

- Find a way to set the instanceType literals to their fixed value but make the attributes Mandatory in the API, `instanceType: Literal['Condition'] = 'Condition'` sets the value but thinks it is a default and thus optional.
- Consider, in the API, separating the target classes into different relationships. The model is OK (it is logical)

**Comment by BSnoeijerCD** [comment]
suggested solution for API to add context:
- contextActivityIds / contextScheudeludeActivityInstanceIds
- appliesToActivityIds / appliesToProcedureIds / ...

We can also leave to see what suggestions we get from public review.

Ids should always be unique throughout the classes. (no doubles in different classes).

**Comment by BSnoeijerCD** [comment]
Replied to accenture:
The API will be updated regarding the mandatory issue for instanceTypes. They will become mandatory in version 2.9.

For version 3.0 we only plan a few minor changes. This includes a few name changes (1 class name and a few attribute names) and some class relation changes.

For ticket 228, we wanted to confirm that ids should be unique throughout the different classes in USDM. So that can be checked indeed. In addition, all referenced Ids anywhere in the model (indicated by id or ids at the end of the reference name in the API) should exist elsewhere in the model. That includes ContextIds and ApplyToIds (note that this last name will slightly change in the API).

Further implications will be evaluated after this sprint.

**Comment by dih-cdisc** [comment]
This was handled and incorporated into release 2.10 so will close
