### ISSUE TITLE
Resolve issue with brackets in IG attribute list [CT]

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#299]
Square brackets are now interpreted in the IG as an reference link.
The tool for creating the CT overview list for the IG needs to add escape characters to the CT text in order to resolve this issue.

**Comment by dih-cdisc** [comment]
Given that tooling appears to be OK for release 3, going to close this ticket.

**Comment by dih-cdisc** [comment]
Reopen issue as apparently the issue still exists

**Comment by drewcdisc** [comment]
@gerrycampion  @dih-cdisc We are looking at a possible solution solely within the content.  We will get back in touch if further tooling work needs to be done.

**Comment by ASL-rmarshall** [comment]
I did some investigation and found that the unwanted hyperlinks are not created if the markdown is copied from GitHub and then pasted into the wiki page using the add Markup function:

![image](https://github.com/user-attachments/assets/4d715bf8-1031-4499-8f09-54851fa76cd5)

and selecting the "Markdown" option:

![image](https://github.com/user-attachments/assets/4f21c4af-75a7-480f-828a-6dd85972232d)

No tooling changes are required if this method is used to insert the markdown into the IG

**Comment by ASL-rmarshall** [comment]
It looks like a modification was made to the original terminology definition for the Study entity to try to prevent the hyper link issue (possibly the "solution solely within the content" mentioned in the [comment above](https://github.com/cdisc-org/DDF-RA/issues/299#issuecomment-2107460269)) - "[ClinicalTrials.gov]" was changed to "[[http://ClinicalTrials.gov]]".  When the markdown is now inserted into the the IG using the method described in the previous comment, this modified text appears as defined in the content (i.e., with the double square brackets and the "http://" that did not appear in the original terminology definition), which is not ideal.

We discussed this at the scrum meeting on 2024-11-12 and agreed to remove "[[http://ClinicalTrials.gov]]" completely from the definition of the Study entity (C15206) because we actually just want to use the defined CDISC Glossary description, which does not contain the reference to ClinicalTrials.gov.

@EMuhlbradt 
FYI @BSnoeijerCD @dih-cdisc
