### ISSUE TITLE
Interventions

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#316]
Formulation missing from intervention + alignment with IDMP

See [JIRA 520](https://jira.cdisc.org/browse/DDF-520)

| Item  | Ticket |
| ------------- | ------------- |
| Model |  #443 |
| CT |  #444 |
| API | #445 |
| Rules | #446 |
| IG | #447 |
| Test Data | #448  |

**Comment by BSnoeijerCD** [comment]
See original Sketch for the intervention classes. We were unsure where to add formulation.<img width="1180" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3U0QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bb41795e8d6abb67ba28bcbd245d01b4aafab57c/OriginalSketchDave.png" alt="OriginalSketchDave.png" />

**Comment by dih-cdisc** [comment]
From @BSnoeijerCD email

Furthermore, per protocol I indicated what intervention information could not yet be stored in USDM. See the summary below:
 
- Packaging of the Drug (1 study)
- Dosage formulation (4 studies)
- Manufacturer/who provides medication (3 studies)
- Substance(s) within the tablet (1 study)
- Other details of the specific drug like molecular weight, pKa, pH etc (1 study)
- No option to store information on Extended release (1 study)
- No option to store information on Storage condition (1 study)
- No option to store the intervention Alias name (1 study)
- Indication whether the intervention is allowed / disallowed concomitant medication (1 study)
- Indication for treatment of expected AEs when occurring (1 study)
 
Based on the above, I would say that kind of a generic interventionProperty class could work for a number of these items?
 
Other model issues:
- Administration information is not always available in the protocol while required by the USDM relationship (1 study). (Note: Also in case on non-drug interventions you would not expect administration details)
- In case of described dose interruptions for specific situations – should DurationWillVary be set to Y? Or, since the interruption is not the standard set to N?
- If the administration duration is not fixed like for the Parkinson study then I have no quantity for duration. However, this variable is required in USDM.

**Comment by dih-cdisc** [comment]
Made this a more general ticket for interventions

**Comment by BSnoeijerCD** [comment]
Observational studies should not include an intervention. 
Types of interventions in Type CT we do not handle yet:
- Devices
- Dietary
- Procedure / Behavioral therapy
- Radiation
To discuss whether we want to include this or in those cases leave it at the intervention level.
Moving the relationship duration directly out of studyIntervention will help. Then it also applies to other types of interventions.

**Comment by BSnoeijerCD** [comment]
@dih-cdisc : see sketch below based on the following considerations:
- Administration can be made more generic as it does not always have to be an agent. So, I like to suggest to change name to AdministrationConcept, AdministrationDetail or Administration instead with the following advantages: 
     -  reuse of frequency, duration and potentially also dose/route and other general attributes for non-agent administrations like questionnaires, behavioral therapy, or other types of interventions that can be specified in intervention.type
     -  all information on procedures regarding the administration and corresponding processes of any intervention are then stored in the same class with the same logic.
- Based on the protocols we have reviewed there is quite a big list of potential properties of an agent or other intervention. I suggest to add a more generic class to cover this which is similar to biomedicalConceptProperties. So I called this interventionProperty. This could contain properties directly linked to the intervention like formulation, packaging, drug provider, pH/pKa, manufacturer or provider, storage condition, but also the institute that developed a questionnaire/method etc.  We could add a type to this one. pharmacologicClass is probably then also more suitable in this new class.
- In some cases the drug ingredients are specified as well including strength, molecular weight etc. To align with IDMP and FHIR, I like to suggest a interventionSubstance class that then can contain those specific attributes if needed. 

![Interventions_suggested updates](https://github.com/cdisc-org/DDF-RA/assets/138679324/51598c21-f779-42f1-88aa-148c9e45c4a1)

**Comment by BSnoeijerCD** [comment]
2 more considerations to note:
- In CPT there is a variable for current/former name(s) or alias(es). I also saw this in one of the example protocols. So how should that be stored
- Maybe we need an in-between separate class for formulation between substance and studyintervention that serves as a containter for 1 or more substances. In FHIR this is called: MedicinalProductDefinition. See https://build.fhir.org/medicinalproductdefinition.html -> I will make an updated scheme based on this.

**Comment by BSnoeijerCD** [comment]
**Aligning to ISO IDMP** 
- The use of ISO IDMP is a regulatory requirement according to the Commission Implementing
Regulation (EU) No 520/2012 (articles 25 and 26) which mandates the use of ISO IDMP for the
exchange of information on medicinal products across the European Union. See [https://www.ema.europa.eu/system/files/documents/other/wc500217406_en.pdf](url)
- EMA is implementing the standards in a phased programme based on the four domains of master data in pharmaceutical regulatory processes: substance, product, organisation and referential (SPOR) master data.  / Product and substance information included in regulatory submissions can be provided in an ISO IDMPcompatible format.[https://www.ema.europa.eu/en/human-regulatory-overview/research-development/data-medicines-iso-idmp-standards-overview](url)
-

**Comment by BSnoeijerCD** [comment]
@dih-cdisc  See here the proposal based on the IDMP / FHIR alignment (based on references above). The ingredients/substance part is complex in IDMP. The below proposal simplifies that part a bit as we do not have to include everything for a clinical study. However in this way it still can be mapped to IDMP/FHR. See also the notes below for the parts that I did not yet address.
![Interventions_12Jul24](https://github.com/user-attachments/assets/b63ea8b2-2edc-459f-b31e-dd7772722263)

- Packaging of the Drug (1 study) => is a whole separate part in IDMP -> we can add this / simplify by 1 text attribute or direct them to the notes for this.
- Other details of the specific drug like molecular weight, pKa, pH, storage condition etc (1 study) -> we can add this as a list of characteristics linking to a value.
- No option to store information on Extended release (1 study) -> FHIR indicates to add this as characteristics
- Indication whether the intervention is allowed / disallowed concomitant medication (1 study) -> add to role CT?
- Indication for treatment of expected AEs when occurring (1 study) -> add to role CT?

For rules: note that the EMA IDMP implementation guide indicates that the StrengthLowerLimit should always be filled and the StrengthUpperLimit only when it concerns a ratio (to be verified).

**Comment by BSnoeijerCD** [comment]
Note: page 37 of chapter 2 of the EU ISO IDMP IG indicates that "medicinal products may consist of two pharmaceutical products that correspond with two different administrable dose forms (e.g., hard capsule and cream) that form individual entities which do not need combining for administering to the patient. In this case the RMS list “Combination Package” shall be used. 
For clinical drugs this combination is tested and more likely seen as two different interventions. Therefore, it is probably more appropriate to use the term PharmaceuticalProduct or the corresponding FHIR name AdministrableProductDefinition instead. See https://build.fhir.org/administrableproductdefinition.html. THis includes attributes like administrableDoseForm and routeOfAdministration. 
I will update the proposal accordingly tomorrow morning.

**Comment by BSnoeijerCD** [comment]
@dih-cdisc @ASL-rmarshall @EMuhlbradt @czwickl : see first version of new UML below (not yet uploaded to Github). I have not yet moved pharmalogicalClass and productDesignation as I first like to dive into the fhir property types. Feel free to comment on names and referential integrity. To be continued on Monday.<img width="821" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWttQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a08b7b36069e871595cacdb35a80fae2d6ed8244/Interventions.png" alt="Interventions.png" />

**Comment by BSnoeijerCD** [comment]
@dih-cdisc @ASL-rmarshall :
Interesting example from a Huntington Disease study. 1 intervention can include multiple tablets of different strengths. These would be different administrableProducts which implies that there should be a 0..* relationship from studyIntervention to AdministrableProductDefinition. 
Also, the same administrableProduct is reused across different interventions for the same study implying that for the API this should not be nested within the StudyIntervention class. See original table and my interpretation for the USDM below.
<img width="527" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGt2Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cb19ccb45680f5cc69e1893bdcfd8d3b9486be7b/Combi_InterventionExampleTable.png" alt="Combi_InterventionExampleTable.png" />
<img width="1153" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOG92Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fc30160b812bee0ac9b7bd7b7d75931972017a8e/Combi_InterventionExampleScheme.png" alt="Combi_InterventionExampleScheme.png" />

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @czwickl :
See annotated UML below for you to work with. 
<img width="821" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3d3Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4d7a0eb31f00ab55f2837939851de5aa5c53060e/Interventions_annot2.png" alt="Interventions_annot2.png" />

**Comment by EMuhlbradt** [comment]
> @EMuhlbradt @czwickl : See annotated UML below for you to work with. <img alt="Interventions_annot2.png" width="821" src="https://camo.githubusercontent.com/69b91a83d5896186dc7e47dc60742bcb99a47db7039105db27cf7ff955a3634b/68747470733a2f2f6170692e7a656e6875622e636f6d2f617474616368656446696c65732f65794a66636d467062484d694f6e73696257567a6332466e5a534936496b4a42614842424c336433516d633950534973496d563463434936626e56736243776963485679496a6f69596d7876596c39705a434a3966513d3d2d2d346437613065623331663030616235356632383337393339383531646535616135633533303630652f496e74657276656e74696f6e735f616e6e6f74322e706e67">

@BSnoeijerCD can you re-post in a different format so I can access it? I can't open png from Github for some reason.

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @czwickl  Apparently the upload in the zenhub environment dose not work. Is this better?
![Interventions_annot2](https://github.com/user-attachments/assets/9159f368-a64f-40e1-baad-aad4f3e90a27)

**Comment by BSnoeijerCD** [comment]
@dih-cdisc @ASL-RMarshall @czwickl @EMuhlbradt 
I have gone through 7 different studies now and came to the conclusion that 
- given that an intervention is in a number of these randomly selected cases a combination of active and/or placebo tablets, it is better to reference the administrableProductDefinition from the Administration class instead of the StudyInterventionclass. In that way we can link an intervention to different administrations (for example: 1 placebo tablet and 2 10 mg tablets) and define for each administration the corresponding frequency, dose and product definitions. See examples in attached document. 
- in case of placebo, there is an administrableProduct describing that it matches the active product but often no ingredients are defined. So the relationship to ingredients should be 0..* instead of 1..*.
- in case of placebo a dose is not defined (and also not for other kinds of administrations like questionnaires or psychological interventions) so the dose relationship to quantity should be 0..1 instead of 1.
- there was 1 case that defined a longer list of ingredients. so if a sponsor wants to define the accompanying ingredients it is helpful to define whether the ingredient is active. We can use maybe a limited list of FHIR and make it extensible for this.
- in all cases the provider (usually the sponsor but might be different) is specified. I will see how this best can be stored in alignment with IDMP.
[Intervention details StudyExplore Jul24.docx](https://github.com/user-attachments/files/16499661/Intervention.details.StudyExplore.Jul24.docx)

We can discuss at the scrum tomorrow and hopefully decide to make these (small) changes.

**Comment by EMuhlbradt** [comment]
> @EMuhlbradt @czwickl Apparently the upload in the zenhub environment dose not work. Is this better? ![Interventions_annot2](https://private-user-images.githubusercontent.com/138679324/355152520-9159f368-a64f-40e1-baad-aad4f3e90a27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NzY1NzUsIm5iZiI6MTcyMjg3NjI3NSwicGF0aCI6Ii8xMzg2NzkzMjQvMzU1MTUyNTIwLTkxNTlmMzY4LWE2NGYtNDBlMS1iYWFkLWFhZDRmM2U5MGEyNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNVQxNjQ0MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZmI2YzZiZWRjNGJhNTQyZjM0NjcwMjUyZDk5MmM2OWU1NzVhODllMTkwNjQxYjgyYWExZjkwNzNlZGNjOTkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.W_nYz_1pCFkZHTueegT_nimwryX32s1Qgtzqj4twEfk)

Much better, thank you @BSnoeijerCD !

**Comment by BSnoeijerCD** [comment]
I made the following changes to the UML (and uploaded to Github) based on our discussions today:
- moved administrableProduct reference to administrations class
- changed cardinality for frequency, route and dose to 0..* to allow for different (partial) specifications (including observational parts).
Desired property types will be further explored based on input of the scrum today. 
![Interventions_annot3](https://github.com/user-attachments/assets/c9554cee-dc4e-43cb-9481-ad172ca2043b)

**Comment by BSnoeijerCD** [comment]
@dih-cdisc @ASL-rmarshall @EMuhlbradt @czwickl 
Although IDMP covers manufacturer in the medicinal product definitions this might be slightly different then the provider/sourcing that is defined in most of the protocols I tested. The provider/sourcing is directly linked how it is done in the clinical study. Therefore, I would not use IDMP manufacturer for this.
However, given the many instances of protocols that are including this information item, it would be beneficial to include sourcing/provider in the model. As this links to organizations and the corresponding structure, I propose to handle the sourcing/provider part of interventions in ticket #293. 
We need to consider then whether this would be on the level of AdministrableProductDefinition which would be beneficial if the intervention is the testing of interaction of multiple drugs or at the higher StudyIntervention level.

**Comment by EMuhlbradt** [comment]
@BSnoeijerCD @dih-cdisc @czwickl please see the attached draft terminology for this ticket. Note that we have questions in the yellow highlighted cells.
[316-444.xlsx](https://github.com/user-attachments/files/16532286/316-444.xlsx)

**Comment by BSnoeijerCD** [comment]
@dih-cdisc @EMuhlbradt @ASL-rmarshall @czwickl 
Based on my experiences with real-world pharmacy data I should have known that multiple specifications of strengths (lower and upper limits) are possible for 1 ingredient. I missed that before in the EMA IDMP IG. See examples below from IDMP IG (chapter 2, Page 193):
![StrengthExampleIDMPIG](https://github.com/user-attachments/assets/487f8e54-2854-473b-86ed-f24bf9f851ab)


This implies that the references strengthLowerLimit and strengthUpperLimit should be 1..* and 0..* respectively and names should be changed to strengthLowerLimit**s** and strengthUperLimit**s**

**Comment by BSnoeijerCD** [comment]
> @BSnoeijerCD @dih-cdisc @czwickl please see the attached draft terminology for this ticket. Note that we have questions in the yellow highlighted cells. [316-444.xlsx](https://github.com/user-attachments/files/16532286/316-444.xlsx)

Thank you @EMuhlbradt See my reactions in the last column.
[316-444_BS.xlsx](https://github.com/user-attachments/files/16539325/316-444_BS.xlsx)

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @dih-cdisc @czwickl
AdminstrableProductProperty.types that I believe should be included:
- pH   (C-Code C45997)
- storage condition
- pharmacological Class (C-Code C98768 - can then be removed from studyIntervention - but needs a code attribute)
- product designation  (can then be removed from studyIntervention - but needs a code attribute)
- Storage condition
- Packaging (e.g. sealed container etc)
For the rest it can be extensible.

Regarding the other optional types considered:
- release form is included in the CDISC CT for administrableDoseForm so does not have to be specified separately in our model.

**Comment by BSnoeijerCD** [comment]
As discussed during scrum today:
- regarding AdministrableProductDefinition: Review and remove definition part from class name. Fhir definition: "A medicinal product in the final form, suitable for administration - after any mixing of multiple components".
- Strengths - give more examples before we change anything
- We do not move ProductDesignation to AdministravleProductDefinition as it is not a feature of the product.
- We need to explore what information goes into pharmacologicClass before we decide to move it.

**Comment by BSnoeijerCD** [comment]
@dih-cdisc @ASL-rmarshall @czwickl @EMuhlbradt 
regarding pharmacologicClass see the CDISC page regarding the terminology to be used: https://www.cdisc.org/kb/known-issues/tsparm-pharmacological-class-terminology-change
It looks medication - related so could link more to the product instead of the intervention which motivates that the attribute can move to the new class. 
Need to check some examples of this terminology on the NCI website.

**Comment by BSnoeijerCD** [comment]
@ASL-rmarshall @EMuhlbradt @czwickl @dih-cdisc 
See below updated annotated UML based on the discussions today. I applied the following changes:
- renamed AdministrableProductDefinition class to AdministrableProduct
- moved attribute pharmacologicClass to AdministrableProduct (it was before in the StudyIntervention class)
- Added name, label and description attributes to the Strength class
- Made strengthLowerLimit and strengthUpperLimit plural and renamed to strengthsLowerLimit and strengthsUpperLimit

**Comment by BSnoeijerCD** [comment]
@dih-cdisc @EMuhlbradt @czwickl @ASL-rmashall 
Please find attached the instance examples based on 9 randomly selected studies from clinicaltrials.gov. 

[InstancesExamples.xlsx](https://github.com/user-attachments/files/16610623/InstancesExamples.xlsx)

Note that as administrableProducts are often repeated for different interventions, it would be good to nest them in the API at the StudyVersion level. Then they can also be reused across multiple designs with the same study drug.

**Comment by ASL-rmarshall** [comment]
@BSnoeijerCD I was originally looking at the modelling from the point of view of working out how it should be used and which rules would be required.  I hadn't looked at the IDMP IG, but I have now.  As discussed on 2024-08-16, the focus of the modelling is to accommodate what's needed to for a study definition, bearing in mind the EMA IDMP IG requirements and - if needed - with reference to FHIR resources.

I agree that basis is not required because it's not typically specified in a study definition.  I also agree that a lot of the detailed FHIR modelling is not required.

However, I think there are some tweaks that could be applied to the modelling that would simplify things a bit, align with existing USDM modelling, make it easier to create and check for conformant data, and eventually meet the EMA IDMA requirements.  The following diagram shows these tweaks:
![Interventions 2](https://github.com/user-attachments/assets/4ce9a650-8ae6-4a3c-b2d3-3e3681651b68)
These are the 4 suggested changes:
1. Make numerator range a property of the strength instead of having two independent strength specifications.  In the diagram, I've shown this as:
    - A second `numerator` relationship to the `Range` class.  I changed the cardinality for the original `numerator` relationship from from 1 to 0..1 because numerator can be specified as either a quantity or a range. We'd need a rule to check that a numerator is specified (either as a quantity or a range). Note that I also modified the `unit` relationship for `Range` to point to `AliasCode` instead of `Code` to be consistent with the `unit` relationship from `Quantity`.  An alternative would be to not use the `Range` class and instead have `numeratorLow` (1) and `numeratorHigh` (0..1) relationships to `Quantity` (similar to [FHIR RatioRange](https://www.hl7.org/fhir/datatypes.html#ratiorange)), but that's less in line with existing USDM modelling.
    - Replacing the `strengthsUpperLimit` and `strengthsLowerLimit` relationships with a single `strengths` relationship.

    This has the following advantages:
    - You don't have independent strength specifications for ranges, meaning that:
        - You don't need a rule to check for "low" strengths corresponding with any "high" strengths (which would probably have to be based on text matching between strength names)
        - You don't need a rule to check that the same unit is used for the denominator in high and low strengths (which would again have to be matches by textual names)
    - This is more in line with how strength ranges are specified in the protocol (e.g., "95-100 mg/ml" instead of "95mg/ml-100 mg/ml" or "88-90 mg in a vial" instead of "88 mg in a vial-90 mg in a vial")
    - It aligns with FHIR but is still mappable to EMA IDMP.
2. Rename the `reference` relationship on `Ingredient` to `references` and change the target cardinality from 0..1 to 0..*. According to both EMA IDMP and FHIR, you can have more than one reference strength.
3. Optionally add something like a `role` attribute/relationship to `Ingredient` - see [FHIR Ingredient.role](https://www.hl7.org/fhir/ingredient-definitions.html#Ingredient.role) and [associated value set](https://www.hl7.org/fhir/valueset-ingredient-role.html). This is not 100% necessary, but it would facilitate:
    - Checking (e.g., ingredients that are starting materials for active ingredients are expected to have a reference strength, a referenced ingredient must be an active ingredient, etc.)
    - Mapping to EMA IDMP and FHIR
4. Optionally add something like a `type` attribute/relationship to `Strength` to differentiate "presentation" and "concentration".  This is not 100% necessary, but it would potentially facilitate:
    - Checking (different types of denominator unit for presentation vs concentration strengths, not more than one strength of each type, etc.)
    - Mapping to EMA IDMP and FHIR

@dih-cdisc

**Comment by EMuhlbradt** [comment]
@BSnoeijerCD @dih-cdisc @czwickl see the attached file containing what we hope is the draft final new terms and changes to existing for this ticket. @BSnoeijerCD there is one outstanding question in row 20 in the 'new' tab.
[316-444_Draft final.xlsx](https://github.com/user-attachments/files/16636750/316-444_Draft.final.xlsx)

**Comment by BSnoeijerCD** [comment]
@dih-cdisc @EMuhlbradt @czwickl 
Erins question is about reference as well and relates to what Richard indicates above in point 2. 
The related citations from the IDMP IG are below:
"Reference strength represents the strength (quantitative composition) of the active moiety of the active substance or of another substance used to express the strength of the product. There are situations when the active substance and active moiety are different resulting in different expression of the strength.
For example, if an active substance is in the form of a salt or hydrate, the reference strength shall be expressed in terms of the mass [or biological activity in International (or other) units where appropriate] of the active moiety (base, acid or anhydrous material).
The reference substance and reference strength of the active substance(s) contained in the Pharmaceutical product or Manufactured Item can be found in section 2. Qualitative and Quantitative Composition of the corresponding SmPC.
The reference strength shall be provided for active substances and is repeatable. However, there are cases where the reference strength of the active substance may not be provided. 
In cases where the quantitative composition of the excipient(s) and/or adjuvant(s) of the medicinal product is not reported in the relevant product information (i.e., SmPC), the substance strength is to be left empty and the substance reference strength is to be completed."

See also examples in [Chapter 8 of IDMPIG](https://www.ema.europa.eu/en/documents/regulatory-procedural-guideline/product-management-service-pms-implementation-international-organization-standardization-iso-standards-identification-medicinal-products-idmp-europe-chapter-8_en.pdf) - starting on page 38

This indicates that indeed there can be more than 1 reference strength.

**Comment by BSnoeijerCD** [comment]
@dih-cdisc @EMuhlbradt @czwickl 
Based on the discussions today. See the updated UML below with the two outstanding questions indicated as well.
<img width="812" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFpwQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--06ae1bd1ffb74f07654e04649ddaf5895027e807/Interventions_Annot6.png" alt="Interventions_Annot6.png" />

**Comment by BSnoeijerCD** [comment]
@dih-cdisc @EMuhlbradt @czwickl 
I updated the list with instances and added a number of examples from IDMP Chapter 8. See attached. [InstancesExamples_v2.xlsx](https://github.com/user-attachments/files/16661625/InstancesExamples_v2.xlsx)

**Note:** that there was only 1 ingredient in the examples from IDMP (and none found in the selected protocols) that had a range for strength and this was an excipient and not an active ingredient. 
Given that and for a better understanding of the model when not IDMP related, I am now in favor of the suggested change from strengthsUpperLimit and strengthsLowerLimit relationships to 1 strengths relationship with the option to define a minValue and maxValue (using range class) for the numerator instead of value (using quantity class). 
The first row of this file indicates the paths according to the model version in the comment above. The second row in this files indicates the paths when this is changed.

**Note:** IDMP requires a reference strength for the active substance while the original strength might be missing. This information is missing in vaccine examples in the IDMP.

**Comment by BSnoeijerCD** [comment]
@dih-cdisc @EMuhlbradt @czwickl 
Please see the last updated version of the UML below (also uploaded to github). The last changes are based on our discussions earlier today. I indicated all intervention changes in yellow and the new changes in orange.
![Interventions_Annot7](https://github.com/user-attachments/assets/2271f465-663e-4b9b-8c03-cdff8c585dd9)

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @czwickl: This is the link for the ingredient role: https://www.hl7.org/fhir/valueset-ingredient-role.html

**Comment by EMuhlbradt** [comment]
@dih-cdisc @BSnoeijerCD Final changes are ready for QC in the Github CT deliverables folder.

**Comment by BSnoeijerCD** [comment]
Thank you @EMuhlbradt @czwickl 

Based on my review I have the following comments:
- AgentAdministration should be changed to Administration - The reason for this is that it can be used more broadly for other types of interventions that can be specified as well like: behavioral therapy, diagnostic test, dietary supplement, radiation, medical procedure etc.
- Since we moved it, should the definition of pharmacologic class be changes to "The pharmacological class of the **administrable** product"?
- With previous links to SDTM codelists you specified that in the "Has value List" column like "Y (SDTM Terminology Codelist ... )". Should the SDTM be specified for administrableDoseForm?
-  referenceSubtance: do we want to be more explicit regarding what is expected here? I put it like this in the IG: "Each active ingredient specified by its substance may have a reference substance, indicating the reference strength once the product is processed in vivo."

**Comment by EMuhlbradt** [comment]
> Thank you @EMuhlbradt @czwickl
> 
> Based on my review I have the following comments:
> 
> * AgentAdministration should be changed to Administration - The reason for this is that it can be used more broadly for other types of interventions that can be specified as well like: behavioral therapy, diagnostic test, dietary supplement, radiation, medical procedure etc.
> * Since we moved it, should the definition of pharmacologic class be changes to "The pharmacological class of the **administrable** product"?
> * With previous links to SDTM codelists you specified that in the "Has value List" column like "Y (SDTM Terminology Codelist ... )". Should the SDTM be specified for administrableDoseForm?
> * referenceSubtance: do we want to be more explicit regarding what is expected here? I put it like this in the IG: "Each active ingredient specified by its substance may have a reference substance, indicating the reference strength once the product is processed in vivo."

1. This should be done
2. Not sure because originally Craig and I decided to keep the semantics completely aligned with the TSPARM value when the attribute was attached to the other Class. Craig and I will need to discuss this as it would require recoding the concept.
3. Fixed 2024-09-03
4. Craig and I will have a look.

**Comment by EMuhlbradt** [comment]
@BSnoeijerCD 
1. Craig and I discussed QC item 2 and have agreed that we should update the semantics (C-code, preferred term, and definition) for both 'pharmacologicClass' and 'administrableDoseForm' to reflect the AdministrableProduct class.
2. Craig and I do not agree to update the relationship definition because we think that clarification belongs in the Implementation guide (i.e., it is not definitional). We think the IG is the more appropriate place to explain what is needed for the referenceSubstance relationship because the examples for this would be so varied/complex. A relationship definition would not be able to encompass all of the nuances of this term (no matter how hard we tried).

**Comment by BSnoeijerCD** [comment]
@dih-cdisc @EMuhlbradt @czwickl @ASL-rmarshall 
I have reviewed the M11 tech spec and protocol with regards to Intervention related attributes. 
See attached Excel for the mappings.
[M11_Intervention_mapping.xlsx](https://github.com/user-attachments/files/16932201/M11_Intervention_mapping.xlsx)

There is one item missing and there are a few notes for discussion regarding whether the mapping is OK or whether something needs to be added/changed in the model.

**Comment by dih-cdisc** [comment]
> @dih-cdisc @EMuhlbradt @czwickl @ASL-rmarshall I have reviewed the M11 tech spec and protocol with regards to Intervention related attributes. See attached Excel for the mappings. [M11_Intervention_mapping.xlsx](https://github.com/user-attachments/files/16932201/M11_Intervention_mapping.xlsx)
> 
> There is one item missing and there are a few notes for discussion regarding whether the mapping is OK or whether something needs to be added/changed in the model.

Deal with the questions within M11 alignment sprints. I just wanted the two compund mappings for now as they are useful for the UDP work and the title page

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @czwickl @dih-cdisc 
As discussed today, I changed substance.code to substance.codes. The corresponding cardinality to the code class is also changed to 0..*. Can you also change the CT and API accordingly?

**Comment by EMuhlbradt** [comment]
> @EMuhlbradt @czwickl @dih-cdisc As discussed today, I changed substance.code to substance.codes. The corresponding cardinality to the code class is also changed to 0..*. Can you also change the CT and API accordingly?

@BSnoeijerCD this has been updated in CT deliverable in 3-6-0 branch during the morning (EST) of 2024-09-11
