### ISSUE TITLE
Protocol Approval Dates

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#37]
Part of Feature #118 

From protocol mapping exercise:

"Approval Date (Comment): Entered as protocol effective date. Actual there are 2 different approval dates on page 1 and 2"

We need to check this through, are there two dates, what are they?

**Comment by EMuhlbradt** [comment]
Erin/Craig: We do not believe that 'Protocol Effective Date' and 'Protocol Approval Date' are the same thing semantically. Protocol Effective Date is in the USDM currently; Protocol Approval Date may be a new attribute.

1. CDISC Protocol terminology contains a term C132352/Study Protocol Version Approval by Sponsor Date:  The date on which a version of the protocol was finalized or approved by the sponsor.
2. Protocols go through other approval steps so its not enough to say 'approval date' generically. Approval 'by whom' is a must have here. Consider modeling similarly to the way organizations were modeled - Date of approval, by whom, and role of approver.

However, we did discuss the idea that a lot of people use the approval date and effective date interchangeably (when something is in effect vs when something takes effect). 'In effect' is potentially the same as approval date, which is why Herve matched these together. We think though that the USDM model element of effective date specifies when the content of the protocol 'takes effect' (ie becomes mandatory). So these should still be two separate concepts.

**Comment by dih-cdisc** [comment]
A thought is how amendments impact this, i.e. an amendment is approved and is then effective which might be two different dates. Also the org approving (assumed to be sponsor?)

Further discussion needed.

**Comment by dih-cdisc** [comment]
Link with #118 M11 will guide us on this topic.

**Comment by drewcdisc** [comment]
After discussion during the Sprint Planning session, we are going to have PBIs for Protocol Approval Dates as part of #118

**Comment by drewcdisc** [comment]
May need to create separate PBIs for API and Model work.

**Comment by BSnoeijerCD** [comment]
Comment Dave: 4.	#37 is small and really part of #118. Do we have one date or two dates. Erin is more of a one date persuasion but let’s just check and be sure. Be wary of Nicola’s comment re versions and dates on the SME call, that has an element of how Novo and OSB does it 😊 though date windows are a common version mechanism, used in ISO11179 if memory serves me correctly.
Craig/berber: At scrum discussed that approval and effective dates are indeed two different things. To include in Protocol & Amendments feature / will be combined for Model and API.

**Comment by dih-cdisc** [comment]
Comment Dave: 4. https://github.com/cdisc-org/DDF-RA/issues/37 is small and really part of https://github.com/cdisc-org/DDF-RA/issues/118. Do we have one date or two dates. Erin is more of a one date persuasion but let’s just check and be sure.
Craig/berber: At scrum discussed that approval and effective dates are indeed two different things. To include in Protocol & Amendments feature / will be combined for Model and API.

**Comment by BSnoeijerCD** [comment]
@daveih @EMuhlbradt @czwickl 
I would say that we at least need for now
- Protocol Approval Date (per version)
- Protocol Effective Date (per version)
And discuss with the SMEs in the Tuesday meeting any use cases for the other two. 
If ok: we can add this as a small discussion item to the 25 Sept SME meeting.

**Comment by dih-cdisc** [comment]
Agree with Berber's thoughts. Just one provisio, what is M11 template doing Erin? We need to match / align with them on this but good clear definitions is important here, what constitutes "approval" versus "effective" but I suspect Erin has that in hand in the M11 work.

**Comment by EMuhlbradt** [comment]
@czwickl @dih-cdisc @BSnoeijerCD the M11 template only has two date (with the following approved draft definitions):
1. 'Version Date': The date on which the document is versioned.
2. 'Sponsor Approval Date': The date that the sponsor approved the current version of the protocol.

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @czwickl @daveih  Comment from Diane: Protocol effective date can vary per site / country (based on approval by ethics committees). So protocol approval date will work. But protocol effective date not in this way. IN M11 it is only approval date.
There is a Sponsor Signature Date in the M11 template though.
In M11 the approval date may also be a link to an included electronic signature.
