### ISSUE TITLE
Safety Objective & Endpoint [API]

### ISSUE THREAD

**Issue by drewcdisc** [cdisc-org/DDF-RA#370]
Do we need safety objective/endpoint in CT. MIght be needed to support old studies?

**Comment by BSnoeijerCD** [comment]
@dih-cdisc : The api still misses notes for:
- Encounter
- Indication
- Condition (inherited)
- AgentAdministration
- StudyDesignPopulation (inherited)
- StudyCohort (inherited)
- StudyElement
- StudyArm
- StudyEpoch

**Comment by dih-cdisc** [comment]
That is because the classes we are adding notes to is:

- Objective
- Endpoint
- BiomedicalConcept
- BiomedicalConceptSurrogate
- BiomedicalConceptCategory
- Activity
- Encounter
- StudyIntervention
- AgentAdministration
- Procedure
- PopulationDefinition and decendants
- Estimand (that is also missing name, label and description which would be helpful)
- AnalysisPopulation

See https://github.com/cdisc-org/DDF-RA/issues/353#issuecomment-2137686226 and https://github.com/cdisc-org/DDF-RA/issues/353#issuecomment-2145021690

Updated the ones missed: 

- Encounter
- AgentAdministration

The inherited ones are covered by SyntaxTemplate

**Comment by BSnoeijerCD** [comment]
- All syntaxTemplate inherited ones are covered in the API except for the Condition one. So could you add that as well?
 - The classes inheriting from AnalysisPopulation e.g. StudyCohort and StudyDesignPopulation were not covered in the API
 - I suggested to add notes to StudyArm, StudyEpoch, StudyElement and Indication classes as well in the UML (See https://github.com/cdisc-org/DDF-RA/issues/353#issuecomment-2150857970) I thought I had mentioned that but indeed did not explicitly. Can you consider them still? They are now already in UML and CT. But if you have concerns we can delete them.
