### ISSUE TITLE
Intervention & Sponsor Reference

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#38]
Class InvestigationIntervention. 

Study intervention often has no coding as it is not registered yet - just a sponsor intervention number

Look into this, look at some protocols for new compounds. Could add a sponsorInterventionReference field (string)?

**Comment by EMuhlbradt** [comment]
Erin/Craig; 
1. Consider using the word 'identifier' instead of 'reference' in this context. Reference is confusing. 
2. More broadly however, wouldn't the existing attribute of 'codes' already handle sponsor-named codes/identifiers for the intervention? It is currently pointing to 'standard' coding/identifying' databases like WHODrug, ATC, etc. but you could also assign a sponsor-defined code to a compound as well.
3. If the 'codes' attribute assigned to InvestigationalInterventions class truly means an identifier for the compound, then the model needs to be flexible enough to allow an intervention to have multiple codes/identifiers assigned to it. Moreover this may require more substantive modeling because each code/identifier assigned to an intervention may have at the very least one additional attribute for the assigning organization name.

**Comment by dih-cdisc** [comment]
I think we can leave this as is and use a sponsor code. InvestigationalIntervention has a description field so a free text option with no codes is available.

I think No Action.

**Comment by dih-cdisc** [comment]
Just check this as part of #40

**Comment by dih-cdisc** [comment]
This is now covered due to #40
