### ISSUE TITLE
Create new test template for CORE USDM v3.0

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#389]

**Comment by ASL-rmarshall** [comment]
@BSnoeijerCD 
The updated test data template for USDM v3.0, [USDM_3.0_Test_Data_Template.xlsx](https://github.com/cdisc-org/ddf-core-poc/blob/main/template-generator/USDM_3.0_Test_Data_Template.xlsx), has been created in the POC repo.

As the POC project is now closed, should the test data template generator be moved into a new repo?  If so, where?

**Comment by ASL-rmarshall** [comment]
I found a minor problem in the test data template when creating test data for the first rule:
- The `instanceType` column is included twice on sheets for specialization classes. Until this problem is addressed in the template generator program the duplicate `instanceType` column should be manually deleted when populating the test data sheet.

**Comment by BSnoeijerCD** [comment]
@ASL-rmarshall : ok. I checked the sheet globally for structures and representation of attributes. All classes are included and for the rest all attributes are represented as far as I checked.
When do you plan to address the instanceType issue?

**Comment by ASL-rmarshall** [comment]
@BSnoeijerCD : the `instanctType` issue is now fixed.
