### ISSUE TITLE
Single & Multi Center Studies

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#39]
Class Study

Do we  need single / multicenter in Study? Compare to CPT, see what is there and example protocols.

See PBIs:
| Item  | Ticket |
| ------------- | ------------- |
| Model |  #234 |
| CT |  #233 |
| API | #235 |
| IG | #236  |
| Examples | #237  |

**Comment by EMuhlbradt** [comment]
Erin/Craig: This concept does not show up very much at all in the eCPT. 
1. Multicenter trials are mentioned in example wording in section 10.1.11/Publication policy: "The sponsor will comply with the requirements for publication of study results. In accordance with standard editorial and ethical practice, the sponsor will generally support publication of multicenter studies only in their entirety and not as individual site data. In this case, a coordinating investigator will be designated by mutual agreement."
2. In section 10.1.10 of the eCPT, they reference study sites, which we think is a similar concept, but again, not much info in the eCPT.
3. Consider getting feedback from SMEs
4. More broadly we question how many studies are truly single center nowadays. Maybe more common in phase I studies? Would this be an indicator type of question: 'An indication as to whether the study is operating at multiple sites'? We acknowledge the model needs to accommodate multicenter studies. Is it really necessary to indicate whether a study is a single or multicenter study? This seems relatively unimportant, particularly since all of the centers involved would be named in the protocol anyway. Alternatively, should the model instead contain information about the location(s) of the site(s) associated with the study.
5. Do they want this info just to pull that information into a syntax template for the Trial Title?

**Comment by dih-cdisc** [comment]
We can discuss with SMEs. I think point 4 above is the relevant. If there are are "slots" for the sites then single / multiple can be derived. 

One aspect of this is when the site info is available, probably later rather than earlier except for Phase 1?

**Comment by dih-cdisc** [comment]
Initial sketch design for adding in Sites. We also need to consider site enrollment as M11 considers this aspect.

![2023 11 21 Site](https://github.com/cdisc-org/DDF-RA/assets/115090009/fa4ab78e-1a74-4294-84d4-2c572a2aa91f)

**Comment by BSnoeijerCD** [comment]
@dih-cdisc : to be consistent should Organization not be inherited by studyIdentifier as well? It has a 1:1 relationship. 

As an alternative: you can also just add relationships from studySite to Organization called oversightCommittee and researchOrganization. That makes the UML less extensive.

**Comment by BSnoeijerCD** [comment]
> > More questions for the team:
> > 
> > * Should enrollment not be "plannedEnrollment"? And how does this align with population?
> > * You indicate a 1:1 relationship for studySites. Are we sure that all study Sites is always specified in the studyDesign phase? I would keep this optional as site recruitment can be done after finalization of the design.
> 
> 1. Intention was, for the site, it is for the actual enrollment when an amendment is created.
> 2. Site would only be there if there were actual sites post study start, hence 1:1. I assume you are referring to the enrollment realtionship

1. Ok. Understood. For clarity, would you consider to link it to amendment then? As an alternative route to enrollment?
2. Sorry for the confusion: I meant the relationship between StudyVersion and StudySite class, which you indicated as 1..* . That implies you always have to specify at least 1 StudySite for each version of the protocol including the number of pts enrolled. At the start this would be 0.

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @dih-cdisc @czwick: see UML below with changes as aligned with Dave.
Based on this: I was wondering whether the relationship should not be from StudyDesign instead of StudyVersion?

![Identifiers, titles and sites](https://github.com/cdisc-org/DDF-RA/assets/138679324/f4222b33-8ccf-4d26-93f1-cc6d35986f43)

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt and @czwickl : this implies the following changes:
- a new class called OversightCommittee inheriting all from Organization class
- a new class called ResearchOrganization inheriting all from Organization class
- a new class called StudySite 
     - Attributes:
            - name
            - description
            - label
     - relationship: 'oversees' to new class OversightCommittee
     - relationship: 'manages' to new class ResearchOrganization
     - relationship: 'currentEnrollment' to class SubjectEnrollment
 - for StudyVersion class (or StudyDesign as I questionned above) a new relationship: 'appliesTo' to new class StudySite

**Comment by gerrycampion** [comment]
Where should OversightCommittee and ResearchOrganization go in the API? Currently they have no parent in the model or api.

**Comment by dih-cdisc** [comment]
Overall changes for release 2.8

![2023 11 20 Conditional](https://github.com/cdisc-org/DDF-RA/assets/115090009/a65dc7c9-f726-400d-8dee-063e72084cef)

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt, @czwickl, @dih-cdisc, @gerrycampion: As discussed during todays scrum: removed Oversight Committee from UML as it is not by definition an organization. Added ticket #253 to reconsider in next sprint.
![Identifiers](https://github.com/cdisc-org/DDF-RA/assets/138679324/2dbc0fc2-b8e4-4742-a9ff-cc91c616985c)

**Comment by BSnoeijerCD** [comment]
@dih-cdisc @EMuhlbradt @czwickl :
Added new ticket #259 to account for organization.type issue. A value is required. However, the current available types do not fit with ResearchOrganization.
