### ISSUE TITLE
Update cardinality for `relativeToScheduledInstance` and `relativeFromScheduledInstance`

### ISSUE THREAD

**Issue by ASL-rmarshall** [cdisc-org/DDF-RA#395]
The IG indicates that `relativeToScheduledInstance` and `relativeFromScheduledInstance` should be specified for every `Timing`, with both referencing the same `ScheduledInstance` for anchor/Fixed Reference timings. If this is the case, the target cardinality for both relationships should be changed from 0..1 to 1.

**Comment by BSnoeijerCD** [comment]
@dih-cdisc , @ASL-rmarshall  I changed the relationship relativeFromScheduledInstance to 1 instead of 0..1 . See annotated UML picture attached.
RelativeToScheduledInstance might not be required if the timing is an anchor. If we require it then is should be filled with the same value as relativeFromScheduledInstance but then we are a bit less flexible. 
<img width="886" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlZyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d0a42a6a2f647274fff6ee0dc1076b97130b3fd2/Timeline_annot.png" alt="Timeline_annot.png" />

**Comment by ASL-rmarshall** [comment]
@BSnoeijerCD If we're leaving the flexibility for `relativeToScheduledInstance` in the model, shouldn't the flexibility also be reflected in the IG?  At the moment the IG says:
> For anchors the relativeTo and relativeFrom nodes should refer to the same scheduled instance.

**Comment by BSnoeijerCD** [comment]
As discussed during scrum today: IG will be updated to reflect this.

**Comment by BSnoeijerCD** [comment]
@ASL-rmarshall @dih-cdisc 
Changed IG to:
For anchors the relativeFrom node should nodes should refer to the same scheduled instance as the relativeTo node or is allowed to be missing.

Only API update needed for relativeFromScheduledInstance cardinality ->  0..1 => 1

**Comment by ASL-rmarshall** [comment]
@BSnoeijerCD 
I think the IG update might be the wrong way round (and it also contains a typo). Something like the following might be better:
> For anchors the relativeFrom node refers to the schedule instance that provides the fixed reference, while the relativeTo node should either refer to the same scheduled instance as the relativeFrom node or it should be missing.

**Comment by BSnoeijerCD** [comment]
@ASL-rmarshall : thank you.
Updated it now as follows:
For anchors, the relativeFrom node refers to the scheduled instance that provides the fixed reference. The corresponding relativeTo node should either refer to the same scheduled instance or should be missing.
