### ISSUE TITLE
CT Code List Extensibility

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#398]
Review DDF CT and add in Extensible flag for all code lists

**Comment by dih-cdisc** [comment]
@EMuhlbradt @czwickl Response to https://github.com/cdisc-org/DDF-RA/issues/398#issuecomment-2176173777

1. Agree
2. Agree
3. Agree, case by case

XL sheet with proposals, all look good. I would make StudyDesign.characteristics Extensible

General question: I think it should be added to DDF deliverable (and thus new column). Only thing we need to make sure is that it does not upset the alignment tool checker with the addition of the new column

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @czwickl @dih-cdisc  :
Checked changes and extensibility. 
1 issue that you might like to account for in the next version:
studyArm.type is indicated as extensible. However as it is Protocol terminology it is not present in the DDF valid value sets sheet. Is this then indicated as such in the protocol terminology?

**Comment by EMuhlbradt** [comment]
@BSnoeijerCD Yes it is indicated as such in the Protocol terminology. I kept it in there because we have a plan in 2025 to deprecate the CDISC Protocol terminology. Any terms that live concurrently in other terminology standards, SDTM, DDF, CDISC Glossary) will stay in those standards and the rest of the 'orphan terms' (that is those terms and codelists not accounted for in other terminology subsets) will be moved to the CDISC Glossary. So when this change happens, that Study Arm Type codelist will be revert to becoming a DDF codelist.

This is all to say though that I think you are correct that we should NOT have that row in the changes file (too confusing) and will deal with it when the time comes in 2025.

**Comment by EMuhlbradt** [comment]
@BSnoeijerCD I have updated the CT changes file and pushed it to the 3-3-0 branch.

**Comment by BSnoeijerCD** [comment]
> @BSnoeijerCD I have updated the CT changes file and pushed it to the 3-3-0 branch.

Yes. I have verified that it is removed from the CT changes file.
