### ISSUE TITLE
Study & Study Design

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#41]
Design type "randomized, parallel, open-label, blind" etc. Can we accomodate this across Study and StudyDesign classes?

**Comment by EMuhlbradt** [comment]
Erin and Craig need more context; we are not sure what the question is here. This appears to be a mix of Intervention Models, Trial Blinding Schemas, etc. This shouldn't be concatenated in the model. Are more attributes needed? 

1. See TSPARM codelist for TBLIND/Trial Blinding Schema (valid values in codelist C66735). This could be a new attribute associated with study design.
2. Blinding and masking are different; interventions are blinded, subject are masked. But one infers the other which is why people use them interchangeably.

**Comment by dih-cdisc** [comment]
Agree with adding TBLIND. I assume this should be added to StudyDesign?

**Comment by dih-cdisc** [comment]
Started a mapping from TS to USDM, see the attached
[TSPARAM.xlsx](https://github.com/cdisc-org/DDF-RA/files/10330428/TSPARAM.xlsx)

**Comment by dih-cdisc** [comment]
TBLIND added, see #44
