### ISSUE TITLE
Fix some CT inconsistencies

### ISSUE THREAD

**Issue by drewcdisc** [cdisc-org/DDF-RA#417]
CT Fixes to make to existing:
1. Activity.label: Update the CDISC Submission value and Definition
2. Recode Class AnalysisPopulation: C188854 to CNEW
3. Update submission value for AnalysisPopulation.description:
4. Update submission value for Endpoint.name and Endpoint.label

Plus any additional ones I find

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @czwickl : while updating the CPT mapping I found another inconsistency that you can take care of:
StudyDesign trialIntentTypes indicates that it uses codelist C66736 - Trial Intent Type Response, while the codelist URL refers to C124307: Treatment Intent. I believe the first one is correct. 
Furthermore, I wonder whether trial Intent type should not be singular instead of plural. The mapping to CPT indicates only one to be filled.

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @czwickl : while updating the CPT mapping I found another inconsistency that you can take care of:
StudyDesign trialIntentTypes indicates that it uses codelist C66736 - Trial Intent Type Response, while the codelist URL refers to C124307: Treatment Intent. I believe the first one is correct. 
Furthermore, I wonder whether trial Intent type should not be singular instead of plural. The mapping to CPT indicates only one to be filled.

**Comment by EMuhlbradt** [comment]
@BSnoeijerCD @dih-cdisc @czwickl see the attached for the full list of changes
[DDF_417.xlsx](https://github.com/user-attachments/files/16067908/DDF_417.xlsx)

**Comment by dih-cdisc** [comment]
> Furthermore, I wonder whether trial Intent type should not be singular instead of plural. The mapping to CPT indicates only one to be filled.

As we discussed yesterday, SDTM TS domain allows for multiple values, hence why USDM allows multiple. Note in IG?

**Comment by BSnoeijerCD** [comment]
> > Furthermore, I wonder whether trial Intent type should not be singular instead of plural. The mapping to CPT indicates only one to be filled.
> 
> As we discussed yesterday, SDTM TS domain allows for multiple values, hence why USDM allows multiple. Note in IG?

Yes. Added this information to IG - CPT mapping of the CPT Primary Purpose variable.

**Comment by BSnoeijerCD** [comment]
> @BSnoeijerCD @dih-cdisc @czwickl see the attached for the full list of changes [DDF_417.xlsx](https://github.com/user-attachments/files/16067908/DDF_417.xlsx)

- Not sure why activity should be changed to Study Activity as class name and relationship to class does not include Study. Also Preferred term change to "Clinical Study Activity Label" might be seen as too restrictive as it might be other activities then clinical activities that are presented in the Schedule of activities.
- Same for endpoints -> not including study there.
- For element - design is included now while this is not the case for endpoints for example. Not sure why it is needed. 
- Encounters can be different from clinical encounters -> Can be an entry of a PRO or call to check whether drugs are taken for example. So I think clinical makes it too narrow.
- Same for eligibility Criteria => not sure why study needs to be added. 

In general/summary: if all other items have Study added then adding that would indeed make it indeed more consistent. Otherwise, I would leave it as is since it is not included in class and or relationship names. 
I would not add clinical to the proposed changes of preferred terms as this can make it too restrictive and confusing.

**Comment by dih-cdisc** [comment]
> > @BSnoeijerCD @dih-cdisc @czwickl see the attached for the full list of changes [DDF_417.xlsx](https://github.com/user-attachments/files/16067908/DDF_417.xlsx)
> 
> * Not sure why activity should be changed to Study Activity as class name and relationship to class does not include Study. Also Preferred term change to "Clinical Study Activity Label" might be seen as too restrictive as it might be other activities then clinical activities that are presented in the Schedule of activities.
> * Same for endpoints -> not including study there.
> * For element - design is included now while this is not the case for endpoints for example. Not sure why it is needed.
> * Encounters can be different from clinical encounters -> Can be an entry of a PRO or call to check whether drugs are taken for example. So I think clinical makes it too narrow.
> * Same for eligibility Criteria => not sure why study needs to be added.
> 
> In general/summary: if all other items have Study added then adding that would indeed make it indeed more consistent. Otherwise, I would leave it as is since it is not included in class and or relationship names. I would not add clinical to the proposed changes of preferred terms as this can make it too restrictive and confusing.

@BSnoeijerCD look at the changes in the context of the whole CT, e.g. for Activity, not the label preferred term is "different" in style to that of name and description.

![Screenshot 2024-07-08 at 11 13 45](https://github.com/cdisc-org/DDF-RA/assets/115090009/60bd9c28-b526-4f4d-8c6e-a3b7fa0e9586)

**Comment by BSnoeijerCD** [comment]
OK. Then is it's good to be consistent and align with the preferred name for the class itself. Also be cautious with using clinical in the label as it might be confusing.

Activity =>use: Activity or Study Activity (**Study Activity** is now the class label)
AnalysisPopulation => Target Study Population for Analysis is now the class label. So I would adjust that one as well to "Analysis Population" then.
StudyEndpoint => Proposed changes are making it consistent. So OK.
StudyElement => Proposed change makes it consistent. So OK.
Encounter => Can we remove clinical everywhere instead of adding it to label as that might be confusing because the encounter does not have to be a clinical one or does not have to be at the clinic?
EligibilityCriterion => Proposed change makes it consistent. So OK.

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @czwickl 
- Checking further I also see that the class name for Study "Clinical Study" differs from the name, description and label preferred name.
- Also the naming in the studyDesignPopulation class is not yet consistent ("Target Study Population" or "Study Design Population")
For the rest it looks good.

**Comment by EMuhlbradt** [comment]
@BSnoeijerCD @dih-cdisc Here is the updated list of changes to go along with this ticket.
[417_2024-07-10.xlsx](https://github.com/user-attachments/files/16163148/417_2024-07-10.xlsx)

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @czwickl :
thank you. Looks good. a few small issues:
- Line 17: I think you forgot to add Study to Eligibility Criterion Text. Or was that on purpose?
- The UML class name or item name Study should **not** be updated to ClinicalStudy (lines 22-25). I was only referring to the preferred term that should be more consistent. Those preferred term changes are ok.

For the rest it is ok

**Comment by EMuhlbradt** [comment]
@BSnoeijerCD @dih-cdisc QA issues above fixed and pushed to Github deliverables in 3-4-0 release.

**Comment by BSnoeijerCD** [comment]
@EMuhlbradt @czwickl 
- As indicated above, for consistency, I believe that the preferred term for EligibilityCriterion.text should be  "**Study** Eligibility Criterion Text"
For the rest all changes indicated in this ticket are well included in USDM_CT.xlsx

**Comment by EMuhlbradt** [comment]
@BSnoeijerCD done and pushed to 3-4-0 release on Github
