### ISSUE TITLE
Resolve alignment.csv issue

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#429]
CT for StudyDefinitionDocumentVersion is not included in alignment.csv while it is in the CT spreadsheet.

**Comment by ASL-rmarshall** [comment]
I suspect the problem is the carriage return that’s embedded in the Definition of StudyDefinitionDocument.versions (cell I452):

> A USDM relationship between the StudyDefinitionDocument and StudyDefinitionDocumentVersion classes which **[HERE]**
identifies the set of versions associated with the study definition document.

This is causing the reading in of the CT file to fail, so everything after this point (i.e., all of the StudyDefinitionDocumentVersion details) are being reported as discrepancies.

Removing the carriage return and re-saving the CT file should fix the problem – I don’t think any coding changes will be needed.

**Comment by BSnoeijerCD** [comment]
Ok. @EMuhlbradt and @czwickl good to check next week by uploading a new version of the CT spreadsheet.

**Comment by dih-cdisc** [comment]
Merci buckets.
Dave

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
