### ISSUE TITLE
Interventions [API]

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#445]
Formulation missing from intervention and alignment with IDMP.
See feature ticket #316

See [JIRA 520](https://jira.cdisc.org/browse/DDF-520)

**Comment by ASL-rmarshall** [comment]
@dih-cdisc I think having `referenceSubstance` as a self-referencing, *definitional* relationship might cause problems with infinite looping. AFAIK, all other self-referencing relationships in the model are references by id.

We are defining a rule to say referenced substances shouldn't have a reference, but an application that parses the API spec directly won't know where to stop.

Off the top of my head, I can think of two alternatives:
1. Define substances in an API-only collection - probably at the StudyVersion level - and reference them (all) by id.
2. Tweak the model to:
    - Remove the `referenceSubstance` relationship from `Substance`
    - Make `Ingredient` a type of `Substance` that can have reference substance(s) in additional to a role (and its `id` attribute and `substance` relationship)
    - Add a `ReferenceSubstance` class that is also a type of `Substance`, but one that can only be referenced by an ingredient 
    - (Substance then becomes an abstract class)

    ![image](https://github.com/user-attachments/assets/38e0cd21-3a1a-411d-99da-11554c4159c1)


I have a slight preference for the second option.

FYI @BSnoeijerCD (and a question: based on your [comment](https://github.com/cdisc-org/DDF-RA/issues/316#issuecomment-2296031228), I was expecting `referenceSubstance` to be changed to 0..* `referenceSubstances` - was keeping it singular intentional?)

**Comment by BSnoeijerCD** [comment]
@ASL-rmarshall  - Repeatable reference strengths were indeed mentioned as such in the IDMP IG. However, there was no example of that in the IG and as it is intended to present **the** active moiety in the body, I am not seeing a use case where this would be applicable for an clinical trial.

**Comment by ASL-rmarshall** [comment]
@dih-cdisc Did you have any thoughts about the infinite looping issue and the two suggested alternatives for preventing it (substance collection vs adding a `ReferenceSubstance` class)?  Is this something that needs to be considered for the 3.6 release?

Here's an updated pic showing `referenceSubstance` as a 0..1 relationship based on Berber's reply above.
![image](https://github.com/user-attachments/assets/83e0ea03-8bc9-4931-a143-2440445e1ee9)

**Comment by ASL-rmarshall** [comment]
This was discussed on 2024-09-11 and the inheritance option was not popular because the IDMP differentiates between ingredients and substances. We'll go with the current model and create a review comment for release 3.6 if it still appears to be an issue.

A simpler alternative might be to move the `referenceSubstance` relationship to be between `Ingredient` and `Substance` (instead of between `Substance` and `Substance`) so that, for each ingredient, you must specify the substance and you may also specify a reference substance:
![image](https://github.com/user-attachments/assets/6723b007-b015-437a-9369-106c9407030e)
