### ISSUE TITLE
Interventions [IG]

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#447]
Formulation missing from intervention and alignment with IDMP.
See feature ticket #316

See [JIRA 520](https://jira.cdisc.org/browse/DDF-520)

**Comment by BSnoeijerCD** [comment]
@czwickl : please see the updated IG for interventions for your review here: https://wiki.cdisc.org/display/USDMIGv4/Study+Interventions

**Comment by czwickl** [comment]
Suggested edits for Study Intervention section of IG:

Paragraph 2:
For each administrable product optionally, information on the pharmacological class, and 1 or more identifiers, properties and ingredients may be specified. Each ingredient specified by its substance may have a reference substance, which is often, for example, used to indicate the identity, substance code,  and strength of the substance itself (as its own reference) or one of the moieties within a substance used as an ingredient (e.g., the free base/acid of the active pharmacologic component when its salt was added as the ingredient).

Paragraph 4:
Note that the internal sponsor code or compound number can be stored as the administrable product identifier.

The logic behind the proposed changes are:
1)	The examples you showed sometimes showed the ingredient substance and the reference substance to be identical, even when they are salts (substance itself as its own reference; and sometimes the free base/acid moiety was used as the reference substance, which will have a separate identity, code, and strength.
2)	I don’t think we should say anything about in vivo or about PK objectives, since these have more to do with what the body does to the product and is determined from analysis of biological specimens than it has to do with the administrable product itself.
3)	The sponsor can assign the formulated product identifier and/or a compound number, but as a general rule we should avoid calling these drugs since a drug is really an approved product with an approved formulation, strength, and dosage form. I know there are examples where the term “drug” might be used in protocols, but strictly speaking, it is a “test article” or an “investigational new drug” and is only classified as a drug after the NDA is approved. Best to avoid the term as it’s not necessary in this case, but up to you.

**Comment by BSnoeijerCD** [comment]
@czwickl thank you for the review. Very helpful.
1. For the reference substance I have now copied the text from the IDMP IG as it is all about the active moiety. "The corresponding reference strength represents the strength (quantitative composition) of the active moiety of the active substance or of another substance used to express the strength of the product. There are situations when the active substance and active moiety are different resulting in different expression of the strength."
2. I left out the PK objectives as you suggested
3. I now added "of the administrable product" since that is also the name of the class it directly relates to and it is more specific.
