### ISSUE TITLE
cardinality of plannedSex for PopulationDefinition

### ISSUE THREAD

**Issue by glow-mdsol** [cdisc-org/DDF-RA#466]
In the sample JSON files, the plannedSex is an array; however in the model the cardinality is 0..1 .  Which of these are expected?

**Comment by dih-cdisc** [comment]
I think from memory it should be an array to allow for MALE, FEMALE but the code list also has a value of BOTH which means an array is not needed ... BUT, I don't like using BOTH, I would rather use MALE or FEMALE or FEMALE, MALE.

@BSnoeijerCD

**Comment by dih-cdisc** [comment]
We can clarify / fix as part of 3.6

**Comment by BSnoeijerCD** [comment]
> I think from memory it should be an array to allow for MALE, FEMALE but the code list also has a value of BOTH which means an array is not needed ... BUT, I don't like using BOTH, I would rather use MALE or FEMALE or FEMALE, MALE.
> 
> @BSnoeijerCD

I remember we adjusted this based on previous discussions / rules.
From a text perspective: using FEMALE and MALE gives us the option to reuse this as text in eligibility criteria. It is more likely that (if specified) they would present it as "male and female subjects" rather then as "subjects of both gender".

From submission perspective: BOTH might be better as that is what you would want to submit.
Let's discuss at scrum today.
@EMuhlbradt @czwickl

**Comment by dih-cdisc** [comment]
Just looking back the mistake appears to have been made between releases 2.6 and 2.7 when Cohorts were added. 

In 2.6 plannedSex was 1: 0..* in the UML. 

In 2.7 with the introduction of PopulationDefinition, it was set to 1:1. It should not have been, it should be a list of codes 1:0..* allowing you to set one or more codes as desired. This allows for [], [MALE], [FEMALE], [BOTH] or  [MALE, FEMALE, BOTH]

Note that the list could be empty (this makes it optional) and this was the subsequent change at release 3 that made it 1:0..1 because of it might be set in the overall population or in a cohort so it needed to be optional, but it was still not a list.

The API has this set as a list which can be empty. I have not checked but I think it has been this way since release 2.6

So we need to tweak the UML to be 1: 0..*

**Comment by BSnoeijerCD** [comment]
- Changed cardinality to 0..2
- Added following text to IG populations section:
The allowed coded values for plannedSex are 'male' or 'female'. Either one, or both can be specified for a study design population or for a study cohort.
- Created corresponding v4.0 rule CHK0232 with text:
A planned sex must ether include a single entry of male or female or both female and male as entries.

@dih-cdisc @ASL-rmarshall: please review
