### ISSUE TITLE
Protocol Amendments [API]

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#475]
Need to ensure that M11 protocol amendments can be supported. Three aspects

1. Amendment support aligns with the updated M11 specification
2. Ensure we can support the detailed rationale for changes. Note we don't need exact details of change as an electronic comparison can be made (see #305)
3. Align with any review comments on Organizations arising from release 3.6. This overlaps because of the need to note enrollment at the time of an amendment being approved.

See feature ticket #469

**Comment by ASL-rmarshall** [comment]
@dih-cdisc @BSnoeijerCD Thinking ahead to how the `appliesTo` relationships for `StudyEnrollment` will be applied in the API, it looks like we may end up with a mix of an `appliesToId` reference for either study sites and study cohorts, and an `appliesTo` definition for geographic scopes.  I don't think this is a problem in itself, modelling-wise - it just seems a bit weird.  What do you think?

This might cause interesting results when checking alignment with the UML and CT - I don't know if that program knows how to deal with a mix. It might think the API has two copies of `appliesTo` (after it's "translated" `appliesToId`).

If we think this will be an issue, we could just rename the "definitional" `appliesTo` relationship to `geographicScope`.

**Comment by ASL-rmarshall** [comment]
The API has been updated to align with [these](https://github.com/cdisc-org/DDF-RA/issues/469#issuecomment-2374054022) model changes.

@dih-cdisc Points of interest:
- I created both `appliesTo` and `appliesToId` in `SubjectEnrollment` and this did not cause any issues.
- I specifically added `description` into `StudyAmendmentImpact` instead of using `ApiBaseModelWithIdAndDesc` because we want `description` to be required (you have to provide a "short descriptive account" of every impact). We used `Masking.description` as a precedent for a description that's required (according to the UML), but when I checked `Masking.description` in the API I found that it was (still) being included as optional using `ApiBaseModelWithIdAndDesc`.  I have therefore modified `Masking.description` in the API to be defined explicitly in the class as a required attribute.  Is this OK or do you think this muddies the use of `description` (i.e., should we use a different attribute name for this sort of required description)?

**Comment by ASL-rmarshall** [comment]
As discussed at the scrum today, the API has been updated to change:
- `description` to `text` in `StudyAmendmentImpact`
- `text` to `summary` in `StudyChange`

We agreed that `description` will be changed to `text` (or something similar) in `Masking` in a later sprint.
