### ISSUE TITLE
Add Syntax Template Capability

### ISSUE THREAD

**Issue by dih-cdisc** [cdisc-org/DDF-RA#48]
See DDF-RA #16  and #120 for background information

Child tickets:

| Item  | Ticket |
| ------------- | ------------- |
| Model | #135 |
| CT | #135 |
| API | #136 |
| IG | #137 |
| Examples | |

**Comment by drewcdisc** [comment]
This will **not** be part of the 2.1 branch.

**Comment by drewcdisc** [comment]
@dih-cdisc We are discussing this item and we are uncertain if you are hoping for this to be delivered this Sprint.  The other option is that we are still refining this item to be delivered in maybe the next Sprint.

Comment?

**Comment by dih-cdisc** [comment]
> @dih-cdisc We are discussing this item and we are uncertain if you are hoping for this to be delivered this Sprint. The other option is that we are still refining this item to be delivered in maybe the next Sprint.
> 
> Comment?

Not for this sprint.

**Comment by BSnoeijerCD** [comment]
Hi @cupkes, @MarkPAndrews and @dih-cdisc ,
I have some questions based on the information in ticket 16
- I now understand that you can have 1 or more dictionaries linking to a list of syntax templates? Would that then be a dictionary for each kind of data? For example an Objectives dictionary, an endpoints dictionary, an eligibility dictionary etc?
- Are you including JSON as content of the attribute parameterMap to define the different references in the templates?
- Do those references then link to the corresponding place in the USDM model? For example if I link to interventions do I then get the content of InvestigationalIntervention? And how does the system know which one to take? Because may be multiple.
