### ISSUE TITLE
Estimands [API]

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#487]
From an @BSnoeijerCD email (related to PHSE estimand paper)

Although we already cover the basics of the estimands we could consider how to further improve it in phase IV by for example:
- Making the analysis populations a sub of the study and/or cohort populations
- Allow reference to intercurrent event variables (either by syntax text templates or other references)  
- Allowing a link to a reference treatment (not in the paper or ICH E9R1 – but proposed by Diane as a logic -> a treatment of interest is often compared to a reference in the analysis)

**Comment by BSnoeijerCD** [comment]
@ASL-rmarshall @dih-cdisc 
If we want to cross-refer the same analysis population and/or the same intercurrent events out of multiple estimands (e.g. reuse them for different estimands) then it might make sense to change the API and put the collection of AnalysisPopulations and IntercurrentEvents in StudyVersion and refer to them instead of nesting them in the estimand class.

**Comment by ASL-rmarshall** [comment]
@BSnoeijerCD @dih-cdisc 
- I think it probably makes sense to have a collection of `AnalysisPopulation`s, though it might be better for this to be in `StudyDesign` instead of `StudyVersion` given that `StudyDesignPopulation` is defined within `StudyDesign` and each `StudyCohort` is defined within a `StudyDesignPopulation`.
- I'm not sure it would be as straightforward for intercurrent events.  At the moment, the model combines strategy with intercurrent event within an estimand, which works OK when your definition of the combination of strategy and intercurrent event is contained within the estimand definition.  However, if we're thinking of splitting things out for reuse (by reference), then I think we'd need to consider where to split things.

    As I understand it, you'd define a set of intercurrent events for a study and then, for each estimand, you'd specify the strategy for handling each of the intercurrent events defined for the study.  Theoretically, different estimands could use different strategies for dealing with the same intercurrent event.

    If we just create a collection of `IntercurrentEvent` within `StudyVersion`, this would actually be a collection of strategies for dealing with intercurrent events - and the same intercurrent event name might appear in the `text` attribute for more than one instance of `IntercurrentEvent`.

    If we wanted to allow a unique set of intercurrent events to be defined for a study, we'd need to separate the intercurrent events from the strategy(ies) used to handle each of them - e.g.:
    ![Objectives, Endpoints, Estimands](https://github.com/user-attachments/assets/849a4cf3-1fed-45de-97dd-a4c33c01467c)
    (I've shown `IntercurrentEventStrategy` as a type of `SyntaxTemplate`, but I guess it could be a standalone class with just `text`)

    In this case, there could be an API-only collection of `IntercurrentEvent`s for the `StudyVersion` (or even a UML/model `intercurrentEvents` relationship from `StudyDesign` to represent the intercurrent events defined for the study), but each `IntercurrentEventStrategy` would remain defined within an estimand.

**Comment by ASL-rmarshall** [comment]
We discussed this at the scrum on 2024-10-28 and agreed that:
- We should move `AnalysisPopulation` into an API-only collection within `StudyDesign` - this makes sense because analysis populations will be shared by multiple estimands.
- We will leave the modelling on intercurrent events unchanged for now - i.e., with `IntercurrentEvent` inheriting from `SyntaxTemplate`, containing a `strategy` attribute, and being nested within `Estimand`. Although splitting intercurrent events from the strategy used to handle them might make sense, there isn't yet a clear enough rationale to justify a change to the model.  We may revisit this once we have additional examples and input from estimand SMEs.

**Comment by ASL-rmarshall** [comment]
The API has been updated so that each `AnalysisPopulation` is now:
- Defined within the new API-only `StudyDesign.analysisPopulations` collection
- Referenced by id in the `Estimand` attribute renamed from `analysisPopulation` to `analysisPopulationId`.
