### ISSUE TITLE
Product designation - Jira ticket

### ISSUE THREAD

**Issue by BSnoeijerCD** [cdisc-org/DDF-RA#508]
See JIRA ticket [526](https://jira.cdisc.org/browse/DDF-526):
The diagram in Section 4.16, Study Interventions has a 1:1 cardinality on the "product designation" link to Code .  This would seem to imply that a study intervention involves a product, though the cardinality of the "administrations" link between Study Intervention Agent Administration allows for zero Agent Administrations.

=> consider to move relationship productDesignation to AdministrableProduct class.

**Comment by ASL-rmarshall** [comment]
@EMuhlbradt @czwickl 
I happened to be looking at the codelist for `productDesignation` ([C207418](https://ncit.nci.nih.gov/ncitbrowser/ajax?action=create_src_vs_tree&vsd_uri=http://evs.nci.nih.gov/valueset/CDISC/C207418)) in the published DDF Terminology spreadsheet (not the USDM_CT spreadsheet) and noticed that it has the following attributes that are not specified in the USDM_CT spreadsheet:
- **Codelist Name**: Study Intervention Product Designation Value Set Terminology
- **Description**: The terminology relevant to the study intervention product designation value set.

Now that we're moving the `productDesignation` relationship from `StudyIntervention` to `AdministrableProduct`, I was wondering how this will be handled:
- Will these codelist-level attributes just be updated to reference "administrable product" instead of "study intervention",
- Will they be left as originally defined,
- Will it be necessary to create a new codelist (with a new C-code) and deprecate the old one, or
- Are terminology changes like this handled in different way?

**Comment by ASL-rmarshall** [comment]
We discussed this at the scrum meeting on 2024-11-21. The C-code for the codelist will be retained and the codelist name and description will be updated to remove the reference to the class - e.g., the Codelist Name will become "Product Designation Value Set Terminology", which is appropriate for use with both:
- `StudyIntervention.productDesignation` (for anyone still using USDM v3.8.0 or before) and
- `AdministrableProduct.productDesignation` (for anyone using USDM v3.9.0 or after).
